// Pure text transforms for the files vltx writes: merges keep what vltx does not own.
import type { Target } from "./target.ts";
import type { PmField } from "./opts.ts";

const HEADER = /^# generated by vlt-lab from profile /;
const KEPT_NPMRC = "# kept from the previous .npmrc";

/** `//host/path/` form used for per-registry auth keys. */
const authKey = (url: string): string => url.replace(/^https?:/, "");

/**
 * .npmrc: vltx owns the default registry, its scope route, auth for its two URLs, ignore-scripts and
 * always-auth. Every other line (other scopes, their auth, unrelated settings) is kept below a marker.
 */
export const mergeNpmrc = (existing: string | undefined, rendered: string, t: Target, alwaysAuth: boolean, prev?: Target): string => {
  const own = alwaysAuth ? `${rendered}always-auth=true\n` : rendered;
  if (!existing) return own;
  const ownAuth = [t, ...(prev ? [prev] : [])].flatMap((x) => [authKey(x.npm), authKey(x.main)]);
  const ownScopes = [t.scope, ...(prev ? [prev.scope] : [])].map((s) => `${s}:registry`);
  const kept = existing.split("\n").filter((raw) => {
    const l = raw.trim();
    if (l === "" || HEADER.test(l) || l === KEPT_NPMRC) return false;
    const key = l.split("=")[0]?.trim() ?? "";
    if (key === "registry" || ownScopes.includes(key)) return false;
    if (key === "ignore-scripts" || key === "always-auth") return false;
    if (ownAuth.some((a) => key.startsWith(`${a}:`))) return false;
    return true;
  });
  return kept.length === 0 ? own : `${own}${KEPT_NPMRC}\n${kept.join("\n")}\n`;
};

type Section = { header: string; lines: string[] };

const sections = (toml: string): { pre: string[]; secs: Section[] } => {
  const pre: string[] = [];
  const secs: Section[] = [];
  for (const raw of toml.split("\n")) {
    const l = raw.trimEnd();
    if (/^\s*\[[^\]]+\]\s*$/.test(l)) secs.push({ header: l.trim(), lines: [] });
    else if (l.trim() === "") continue;
    else (secs.at(-1)?.lines ?? pre).push(l);
  }
  return { pre, secs };
};

const tomlKey = (line: string): string => (line.split("=")[0] ?? "").trim().replace(/^["']|["']$/g, "").replace(/^@/, "");

/**
 * bunfig.toml: vltx owns `[install] registry` and its own entry in `[install.scopes]`. Other keys in
 * those tables and every other table are kept, so bun sees one `[install]` table.
 */
export const mergeBunfig = (existing: string | undefined, rendered: string, t: Target, prev?: Target): string => {
  if (!existing) return rendered;
  const mine = sections(rendered);
  const cur = sections(existing);
  const scopeNames = [t.scope.slice(1), ...(prev ? [prev.scope.slice(1)] : [])];
  const get = (s: { secs: Section[] }, h: string): string[] => s.secs.find((x) => x.header === h)?.lines ?? [];
  const install = [...get(mine, "[install]"), ...get(cur, "[install]").filter((l) => tomlKey(l) !== "registry")];
  const scopes = [...get(mine, "[install.scopes]"), ...get(cur, "[install.scopes]").filter((l) => !scopeNames.includes(tomlKey(l)))];
  const others = cur.secs.filter((s) => !["[install]", "[install.scopes]", "[install.registry]"].includes(s.header));
  const pre = cur.pre.filter((l) => !HEADER.test(l));
  const blocks = [
    [...mine.pre, ...pre, "[install]", ...install],
    ["[install.scopes]", ...scopes],
    ...others.map((s) => [s.header, ...s.lines]),
  ];
  return `${blocks.map((b) => b.join("\n")).join("\n\n")}\n`;
};

type Json = Record<string, unknown>;
const isObj = (v: unknown): v is Json => typeof v === "object" && v !== null && !Array.isArray(v);

/** User vlt.json, example 02 semantics: own config.registries, config.scoped-registries, config.command.build. */
export const mergeUserVltJson = (current: string | undefined, rendered: string): string => {
  const cur: unknown = current ? JSON.parse(current) : {};
  if (!isObj(cur)) throw new Error("vlt.json is not a JSON object");
  const n = (JSON.parse(rendered) as { config: Json }).config;
  if (!isObj(cur.config)) cur.config = {};
  const cfg = cur.config as Json;
  cfg.registries = n.registries;
  if ("scoped-registries" in n) cfg["scoped-registries"] = n["scoped-registries"];
  else delete cfg["scoped-registries"];
  if (!isObj(cfg.command)) cfg.command = {};
  (cfg.command as Json).build = (n.command as Json).build;
  return `${JSON.stringify(cur, null, 2)}\n`;
};

/**
 * Project vlt.json edits vlt config cannot make: add workspace globs (top level) and drop scope routes
 * that pointed at this registry base for another account. Returns the input unchanged when nothing changes.
 */
export const fixupVltJson = (text: string, opts: { workspaces: readonly string[]; dropScopes: readonly string[] }): string => {
  const doc: unknown = JSON.parse(text);
  if (!isObj(doc)) throw new Error("vlt.json is not a JSON object");
  let changed = false;
  if (opts.workspaces.length > 0) {
    const w = doc.workspaces;
    if (w === undefined) {
      doc.workspaces = [...opts.workspaces];
      changed = true;
    } else if (typeof w === "string" || Array.isArray(w)) {
      const list = typeof w === "string" ? [w] : w.map(String);
      const add = opts.workspaces.filter((g) => !list.includes(g));
      if (add.length > 0 || typeof w === "string") {
        doc.workspaces = [...list, ...add];
        changed = true;
      }
    } else if (isObj(w)) {
      const all = Object.values(w).flatMap((v) => (Array.isArray(v) ? v.map(String) : [String(v)]));
      const add = opts.workspaces.filter((g) => !all.includes(g));
      if (add.length > 0) {
        const cur = w.packages;
        w.packages = [...(Array.isArray(cur) ? cur.map(String) : typeof cur === "string" ? [cur] : []), ...add];
        changed = true;
      }
    }
  }
  const sr = isObj(doc.config) ? (doc.config as Json)["scoped-registries"] : undefined;
  if (isObj(sr)) {
    for (const s of opts.dropScopes) {
      if (s in sr) {
        delete sr[s];
        changed = true;
      }
    }
  }
  return changed ? `${JSON.stringify(doc, null, 2)}\n` : text;
};

/** What a project vlt.json must say after configuration; returns the mismatches. */
export const checkVltJson = (text: string, t: Target, buildTarget: string): string[] => {
  const problems: string[] = [];
  let doc: unknown;
  try {
    doc = JSON.parse(text);
  } catch (e) {
    return [`vlt.json is not JSON: ${(e as Error).message}`];
  }
  const cfg = isObj(doc) && isObj(doc.config) ? (doc.config as Json) : {};
  const reg = isObj(cfg.registries) ? cfg.registries : {};
  const sr = isObj(cfg["scoped-registries"]) ? cfg["scoped-registries"] : {};
  const cmd = isObj(cfg.command) && isObj(cfg.command.build) ? (cfg.command.build as Json) : {};
  if (reg.npm !== t.npm) problems.push(`config.registries.npm is ${JSON.stringify(reg.npm)}, expected ${t.npm}`);
  if (reg.main !== t.main) problems.push(`config.registries.main is ${JSON.stringify(reg.main)}, expected ${t.main}`);
  if (sr[t.scope] !== t.main) problems.push(`config.scoped-registries["${t.scope}"] is ${JSON.stringify(sr[t.scope])}, expected ${t.main}`);
  if (cmd.target !== buildTarget) problems.push(`config.command.build.target is ${JSON.stringify(cmd.target)}, expected ${buildTarget}`);
  if (isObj(doc) && ("registries" in doc || "scoped-registries" in doc)) problems.push("registry keys at the top level are ignored by vlt; they belong under \"config\"");
  return problems;
};

/** Indentation used by a JSON file: tab, a number of spaces, or 0 for single-line files. */
const indentOf = (text: string): string | number => {
  const m = /^\{\r?\n([ \t]+)"/.exec(text);
  if (m?.[1]) return m[1].startsWith("\t") ? "\t" : m[1].length;
  return text.trim().includes("\n") ? 2 : 0;
};

export const stringifyLike = (original: string, value: unknown): string => {
  const ind = indentOf(original);
  const body = ind === 0 ? JSON.stringify(value) : JSON.stringify(value, null, ind);
  return original.endsWith("\n") ? `${body}\n` : body;
};

/** package.json `packageManager` handling. Returns the input when nothing changes. */
export const editPackageManager = (text: string, field: PmField, vltVersion: string | undefined): string => {
  if (field === "keep") return text;
  const pkg = JSON.parse(text) as Json;
  if (field === "remove") {
    if (!("packageManager" in pkg)) return text;
    delete pkg.packageManager;
    return stringifyLike(text, pkg);
  }
  const want = { name: "vlt", version: vltVersion ? `^${vltVersion}` : "*", onFail: "warn" };
  const dev = isObj(pkg.devEngines) ? pkg.devEngines : {};
  if (JSON.stringify(dev.packageManager) === JSON.stringify(want) && !("packageManager" in pkg)) return text;
  delete pkg.packageManager;
  pkg.devEngines = { ...dev, packageManager: want };
  return stringifyLike(text, pkg);
};

/** Set package.json name (used by `vltx new`). */
export const setPackageName = (text: string, name: string): string => {
  const pkg = JSON.parse(text) as Json;
  if (pkg.name === name) return text;
  pkg.name = name;
  return stringifyLike(text, pkg);
};

/** .gitignore lines that already keep .vltx/ (backups may hold registry credentials) out of git. */
const VLTX_IGNORES = new Set([".vltx", ".vltx/", "/.vltx", "/.vltx/", ".vltx/*", "/.vltx/*", ".vltx/**", "/.vltx/**"]);

export const gitignoreHasVltx = (text: string | undefined): boolean =>
  text !== undefined && text.split("\n").some((l) => VLTX_IGNORES.has(l.trim()));

/** Append `.vltx/` to a .gitignore (or start one); unchanged when it is already ignored. */
export const addVltxIgnore = (text: string | undefined): string => {
  if (gitignoreHasVltx(text)) return text as string;
  if (text === undefined || text === "") return ".vltx/\n";
  return `${text.endsWith("\n") ? text : `${text}\n`}.vltx/\n`;
};
