#!/bin/sh
# smoke.sh: install one fixture with npm, pnpm, yarn classic, bun and vlt against one registry profile.
#
#   sh smoke.sh [--profile NAME] [--clients npm,pnpm,yarn,bun,vlt] [--out DIR] [--fixture FILE]
#               [--no-warm] [--keep]
#
# Every client gets its own project in a mktemp dir with the profile's project files (.npmrc,
# bunfig.toml, vlt.json) and the profile's env-sh exports, a fresh HOME/XDG tree and a fresh cache.
# Per client it records exit code and wall time of a cold install (empty cache) and a warm one
# (cache and lockfile kept, node_modules removed), whether dependency lifecycle scripts ran
# (script-hook.cjs), the lockfile, the tarball hosts the lockfile names, and the installed versions.
# Writes OUT/<profile>.json and OUT/<profile>.md (OUT defaults to ./results next to this script).
# --fixture takes a package.json with exact dependency versions (default fixture/package.json).
# Exit 0 when every client installed the fixture, 3 when at least one did not (results still written).
set -eu
HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
VL_ROOT=${VL_ROOT:-$(CDPATH= cd -- "$HERE/../../.." && pwd)}
. "$VL_ROOT/lib/sh/common.sh"
usage() { sed -n '2,15p' "$0" | sed 's/^# \{0,1\}//'; }

PROFILE=${VLT_LAB_PROFILE:-}
CLIENTS=npm,pnpm,yarn,bun,vlt
OUT=$HERE/results
WARM=1
KEEP=0
FIXTURE=$HERE/fixture/package.json
while [ $# -gt 0 ]; do
  case $1 in
    --profile) PROFILE=${2:?--profile needs a value}; shift 2 ;;
    --clients) CLIENTS=${2:?--clients needs a value}; shift 2 ;;
    --out) OUT=${2:?--out needs a value}; shift 2 ;;
    --fixture) FIXTURE=${2:?--fixture needs a value}; shift 2 ;;
    --no-warm) WARM=0; shift ;;
    --keep) KEEP=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) usage >&2; exit 2 ;;
  esac
done
vl_need jq npm pnpm yarn bun vlt node date od timeout
[ -f "$FIXTURE" ] || vl_die "fixture not found: $FIXTURE"
FIXTURE=$(CDPATH= cd -- "$(dirname -- "$FIXTURE")" && pwd)/$(basename -- "$FIXTURE")
DEPS=$(jq -r '.dependencies | keys[]' "$FIXTURE")

ENV_SH=$(vl_profile render env-sh "$PROFILE") || vl_die "cannot render profile ${PROFILE:-<default>}"
NAME=$(printf '%s\n' "$ENV_SH" | sed -n '1s/^# generated by vlt-lab from profile \(.*\); do not edit$/\1/p')
NPMRC=$(vl_profile render npmrc "$NAME")
REGISTRY=$(printf '%s\n' "$NPMRC" | sed -n 's/^registry=//p')
TOKEN_ENV=$(printf '%s\n' "$NPMRC" | sed -n 's/.*_authToken=\${\([A-Za-z_][A-Za-z0-9_]*\)}.*/\1/p' | head -n 1)
TIMEOUT=${VL_SMOKE_TIMEOUT:-300}

SCR=$(mktemp -d "${TMPDIR:-/tmp}/vlt-smoke.XXXXXX")
cleanup() { if [ "$KEEP" = 1 ]; then vl_log "kept $SCR"; else rm -rf "$SCR"; fi; }
trap cleanup EXIT
trap 'exit 130' INT TERM

# Isolation: nothing from the caller's user config reaches the clients.
export HOME="$SCR/home" XDG_CONFIG_HOME="$SCR/xdg/config" XDG_CACHE_HOME="$SCR/xdg/cache" \
  XDG_DATA_HOME="$SCR/xdg/data" XDG_STATE_HOME="$SCR/xdg/state"
mkdir -p "$HOME" "$XDG_CONFIG_HOME" "$XDG_CACHE_HOME" "$XDG_DATA_HOME" "$XDG_STATE_HOME"
unset NPM_CONFIG_USERCONFIG npm_config_userconfig NPM_CONFIG_GLOBALCONFIG npm_config_globalconfig \
  BUN_CONFIG_REGISTRY NPM_CONFIG_REGISTRY npm_config_registry VLT_REGISTRY VLT_REGISTRIES VLT_SCOPED_REGISTRIES 2>/dev/null || true
eval "$ENV_SH"
export npm_config_update_notifier=false NO_UPDATE_NOTIFIER=1 YARN_IGNORE_ENGINES=1
export NODE_OPTIONS="${NODE_OPTIONS:-} --require=$HERE/script-hook.cjs"

NOTES=$SCR/notes.txt
: > "$NOTES"
TOKVAL=""
if [ -n "$TOKEN_ENV" ]; then
  eval "TOKVAL=\${$TOKEN_ENV:-}"
  [ -n "$TOKVAL" ] || printf 'token variable %s is not set, so clients send no credentials\n' "$TOKEN_ENV" >> "$NOTES"
  printf 'yarn classic project .npmrc gets always-auth=true (yarn 1.22 sends _authToken only with it)\n' >> "$NOTES"
  if [ "$TOKEN_ENV" != VLT_TOKEN ]; then printf 'vlt receives %s as VLT_TOKEN\n' "$TOKEN_ENV" >> "$NOTES"; fi
fi

lockfile_of() {
  case $1 in npm) echo package-lock.json ;; pnpm) echo pnpm-lock.yaml ;; yarn) echo yarn.lock ;; bun) echo bun.lock ;; vlt) echo vlt-lock.json ;; esac
}
host_of() { sed -n 's#^[A-Za-z+]*://\([^/]*\).*#\1#p'; }

# install_cmd CLIENT CACHE: run the client's install in the current directory (under timeout)
install_cmd() {
  case $1 in
    npm) timeout "$TIMEOUT" npm install --cache "$2/npm" --no-audit --no-fund ;;
    pnpm) timeout "$TIMEOUT" pnpm install --store-dir "$2/pnpm/store" --cache-dir "$2/pnpm/cache" ;;
    yarn) timeout "$TIMEOUT" yarn install --non-interactive --no-progress --cache-folder "$2/yarn" ;;
    bun) BUN_INSTALL_CACHE_DIR="$2/bun" timeout "$TIMEOUT" bun install --no-progress ;;
    vlt) if [ -n "$TOKVAL" ] && [ "$TOKEN_ENV" != VLT_TOKEN ]; then export VLT_TOKEN="$TOKVAL"; fi
         timeout "$TIMEOUT" vlt install --cache="$2/vlt" ;;
  esac
}

now_ms() { echo $(( $(date +%s%N) / 1000000 )); }

# run_phase CLIENT PHASE: prints "exit ms"
run_phase() {
  _p=$SCR/proj/$1
  _t0=$(now_ms)
  (cd "$_p" && VL_SMOKE_SCRIPT_LOG="$SCR/scripts.$1.log" && export VL_SMOKE_SCRIPT_LOG && \
    install_cmd "$1" "$SCR/cache") > "$SCR/log.$1.$2" 2>&1 && _rc=0 || _rc=$?
  _t1=$(now_ms)
  echo "$_rc $((_t1 - _t0))"
}

# error_line LOG: the most telling line of a failed install log
error_line() {
  _c=$(tr -d '\r' < "$1" 2>/dev/null | sed 's/\x1b\[[0-9;]*m//g')
  _l=$(printf '%s\n' "$_c" | grep -E 'ERR_PNPM_|^error |npm error (40[0-9] |notarget)|[Ee]rror: |ECONNREFUSED|ENOTFOUND' | head -n 1)
  [ -n "$_l" ] || _l=$(printf '%s\n' "$_c" | grep -v '^[[:space:]]*$' | tail -n 1)
  printf '%s' "$_l" | cut -c1-220
}

# tarball_hosts CLIENT DIR: "<hosts space separated>|<source>"
tarball_hosts() {
  _d=$2
  case $1 in
    npm)
      _h=$(jq -r '.packages[]?.resolved // empty' "$_d/package-lock.json" 2>/dev/null | host_of | sort -u | tr '\n' ' ')
      echo "$_h|lockfile resolved URLs" ;;
    yarn)
      _h=$(sed -n 's/^  resolved "\([^"]*\)"$/\1/p' "$_d/yarn.lock" 2>/dev/null | host_of | sort -u | tr '\n' ' ')
      echo "$_h|lockfile resolved URLs" ;;
    bun)
      _u=$(sed -n 's/^    "[^"]*": \["[^"]*", "\([^"]*\)".*/\1/p' "$_d/bun.lock" 2>/dev/null | sort -u)
      _h=""
      if [ -f "$_d/bun.lock" ]; then
        _h=$( { if printf '%s\n' "$_u" | grep -q '^$'; then echo registry.npmjs.org; fi
                printf '%s\n' "$_u" | grep -v '^$' | host_of; } | sort -u | tr '\n' ' ')
      fi
      echo "$_h|bun.lock URLs, empty URL means bun's default registry.npmjs.org" ;;
    pnpm)
      _h=$(sed -n 's/.*tarball: \([^,}]*\).*/\1/p' "$_d/pnpm-lock.yaml" 2>/dev/null | host_of | sort -u | tr '\n' ' ')
      if [ -n "$_h" ]; then echo "$_h|lockfile tarball URLs"; else
        _h=$(sed -n 's/^  default: //p' "$_d/node_modules/.modules.yaml" 2>/dev/null | host_of | sort -u | tr '\n' ' ')
        echo "$_h|lockfile has integrity only; default registry from node_modules/.modules.yaml"
      fi ;;
    vlt)
      _h=$(jq -r '(.options.registries // {}) as $r | (.options.registry // null) as $d
          | [.nodes | keys[] | (capture("^~(?<a>[^~]+)~") .a) as $a | $r[$a] // empty]
            + [.nodes | keys[] | select(startswith("··") and ($d != null)) | $d]
          | unique[]' "$_d/vlt-lock.json" 2>/dev/null | host_of | sort -u | tr '\n' ' ')
      echo "$_h|vlt-lock.json registry aliases" ;;
  esac
}

esbuild_bin() {
  _f=$1/node_modules/esbuild/bin/esbuild
  [ -e "$_f" ] || { echo missing; return; }
  case $(od -An -c -N4 "$_f" | tr -d ' ') in
    177ELF) echo native ;;
    *) echo js-shim ;;
  esac
}

ROWS=$SCR/rows.ndjson
: > "$ROWS"
mkdir -p "$SCR/proj" "$SCR/cache"
for c in $(printf '%s' "$CLIENTS" | tr ',' ' '); do
  case $c in npm|pnpm|yarn|bun|vlt) ;; *) vl_die "unknown client $c" ;; esac
  P=$SCR/proj/$c
  mkdir -p "$P"
  cp "$FIXTURE" "$P/package.json"
  printf '%s\n' "$NPMRC" > "$P/.npmrc"
  [ "$c" = yarn ] && [ -n "$TOKEN_ENV" ] && printf 'always-auth=true\n' >> "$P/.npmrc"
  vl_profile render bunfig "$NAME" > "$P/bunfig.toml"
  vl_profile render vlt-json "$NAME" > "$P/vlt.json"
  VERSION=$(cd "$P" && "$c" --version 2>/dev/null | tail -n 1 | sed 's/^v//') || VERSION=unknown

  vl_log "$NAME: $c cold install"
  set -- $(run_phase "$c" cold)
  COLD_RC=$1 COLD_MS=$2
  LOCK=$(lockfile_of "$c")
  LOCK_OK=false; [ -f "$P/$LOCK" ] && LOCK_OK=true
  HOSTS=$(tarball_hosts "$c" "$P")
  INSTALLED=$(for d in $DEPS; do
    v=$(jq -r .version "$P/node_modules/$d/package.json" 2>/dev/null) || v=""
    printf '%s\t%s\n' "$d" "$v"; done | jq -Rn '[inputs | split("\t") | {(.[0]): .[1]}] | add')
  EBIN=$(esbuild_bin "$P")
  ERR=""
  [ "$COLD_RC" = 0 ] || ERR=$(error_line "$SCR/log.$c.cold")

  WARM_JSON=null
  if [ "$WARM" = 1 ] && [ "$COLD_RC" = 0 ]; then
    rm -rf "$P/node_modules"
    vl_log "$NAME: $c warm install"
    set -- $(run_phase "$c" warm)
    WARM_JSON=$(jq -n --argjson e "$1" --argjson m "$2" '{exit: $e, ms: $m}')
    [ "$1" = 0 ] || ERR=$(error_line "$SCR/log.$c.warm")
  fi
  EVENTS=$(awk -F '\t' '{ n = $1; sub(/.*\/node_modules\//, "", n); print n " " $3 }' "$SCR/scripts.$c.log" 2>/dev/null \
    | sort -u | jq -Rn '[inputs | select(. != "")]')

  jq -n --arg client "$c" --arg version "$VERSION" \
    --argjson ce "$COLD_RC" --argjson cm "$COLD_MS" --argjson warm "$WARM_JSON" \
    --arg lock "$LOCK" --argjson lockok "$LOCK_OK" --argjson events "$EVENTS" --arg ebin "$EBIN" \
    --arg hosts "${HOSTS%%|*}" --arg hsrc "${HOSTS#*|}" --argjson installed "$INSTALLED" \
    --slurpfile fx "$FIXTURE" --arg err "$ERR" '
    {client: $client, version: $version, cold: {exit: $ce, ms: $cm}, warm: $warm,
     lockfile: $lock, lockfile_written: $lockok,
     scripts_ran: (($events | length) > 0), script_events: $events, esbuild_bin: $ebin,
     tarball_hosts: ($hosts | split(" ") | map(select(. != ""))), host_source: $hsrc,
     installed: $installed,
     installed_ok: ($fx[0].dependencies | to_entries | all(.value == ($installed[.key] // ""))),
     error: $err}' >> "$ROWS"
done

mkdir -p "$OUT"
jq -s --arg profile "$NAME" --arg registry "$REGISTRY" --arg date "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
  --slurpfile fx "$FIXTURE" --rawfile notes "$NOTES" '
  {profile: $profile, registry: $registry, date: $date, entrypoint: "sh",
   fixture: $fx[0].dependencies, notes: ($notes | split("\n") | map(select(. != ""))), clients: .}' \
  "$ROWS" > "$OUT/$NAME.json"
jq -r -f "$HERE/report.jq" "$OUT/$NAME.json" > "$OUT/$NAME.md"
cat "$OUT/$NAME.md"
vl_log "wrote $OUT/$NAME.json and $OUT/$NAME.md"
if jq -e 'all(.clients[]; .installed_ok and .cold.exit == 0)' "$OUT/$NAME.json" >/dev/null; then exit 0; else exit 3; fi
