#!/usr/bin/env bun
// user-config.ts: apply a registry profile to every client's user-level config.
//
//   bun user-config.ts <diff|apply|restore|status> [--profile NAME]
//                      [--targets npmrc,bunfig,yarnrc,vlt-json,env] [--home DIR]
//
// Same flags and effects as user-config.sh and user-config.nu.
import { copyFileSync, existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { basename, dirname, join, resolve } from "node:path";
import { parseArgs } from "node:util";
import { die, log, run } from "../../lib/ts/common.ts";
import { defaultProfilesPath, loadProfiles, pickProfile, render, type Target } from "../../lib/ts/profile.ts";

const ALL_TARGETS = "npmrc,bunfig,yarnrc,vlt-json,env";
const USAGE = "usage: user-config <diff|apply|restore|status> [--profile NAME] [--targets LIST] [--home DIR]";

type Entry = { target: string; rt: Target; path: string };
type Loc = { home: string; config: string; xdg: boolean };
type Json = Record<string, unknown>;

const doc = loadProfiles(defaultProfilesPath());
const renderFor = (rt: Target, profile: string | undefined): string => render(pickProfile(doc, profile, process.env), rt);
const tryRender = (rt: Target, profile: string): string | undefined => {
  try {
    return renderFor(rt, profile);
  } catch {
    return undefined;
  }
};

/** Paths, computed the way the clients compute them. */
const locations = (home: string | undefined): Loc => {
  if (home !== undefined && home !== "") {
    mkdirSync(home, { recursive: true });
    const h = resolve(home);
    return { home: h, config: join(h, ".config"), xdg: false };
  }
  const h = process.env.HOME ?? die("HOME is not set");
  const x = process.env.XDG_CONFIG_HOME ?? "";
  return x !== "" ? { home: h, config: x, xdg: true } : { home: h, config: join(h, ".config"), xdg: false };
};

const entries = (targets: string, loc: Loc): Entry[] => {
  // bun 1.4 reads $XDG_CONFIG_HOME/.bunfig.toml when XDG_CONFIG_HOME is set, else $HOME/.bunfig.toml
  const bunfig = loc.xdg ? join(loc.config, ".bunfig.toml") : join(loc.home, ".bunfig.toml");
  return targets
    .split(",")
    .filter((t) => t !== "")
    .flatMap((t): Entry[] => {
      switch (t) {
        case "npmrc":
          return [{ target: t, rt: "npmrc", path: join(loc.home, ".npmrc") }];
        case "bunfig":
          return [{ target: t, rt: "bunfig", path: bunfig }];
        case "yarnrc":
          return [{ target: t, rt: "yarnrc", path: join(loc.home, ".yarnrc.yml") }];
        case "vlt-json":
          return [{ target: t, rt: "vlt-json", path: join(loc.config, "vlt", "vlt.json") }];
        case "env":
          return [
            { target: t, rt: "env-sh", path: join(loc.config, "vlt-lab", "env.sh") },
            { target: t, rt: "env-nu", path: join(loc.config, "vlt-lab", "env.nu") },
          ];
        default:
          return die(`unknown target ${t}; expected some of: ${ALL_TARGETS}`);
      }
    });
};

const readRaw = (path: string): string => (existsSync(path) ? readFileSync(path, "utf8") : "");

const isObject = (v: unknown): v is Json => typeof v === "object" && v !== null && !Array.isArray(v);

/**
 * vlt.json merge: vlt-lab owns config.registries, config.scoped-registries and
 * config.command.build; every other key in the existing file is preserved.
 */
const mergeVltJson = (current: string, rendered: string): string => {
  const cur: unknown = current === "" ? {} : JSON.parse(current);
  if (!isObject(cur)) throw new Error("vlt.json is not a JSON object");
  const n = (JSON.parse(rendered) as { config: Json }).config;
  if (cur.config == null) cur.config = {};
  const cfg = cur.config as Json;
  cfg.registries = n.registries;
  if ("scoped-registries" in n) cfg["scoped-registries"] = n["scoped-registries"];
  else delete cfg["scoped-registries"];
  if (cfg.command == null) cfg.command = {};
  (cfg.command as Json).build = (n.command as Json).build;
  return `${JSON.stringify(cur, null, 2)}\n`;
};

const renderEntry = (e: Entry, profile: string | undefined): string => {
  const out = renderFor(e.rt, profile);
  return e.rt === "vlt-json" ? mergeVltJson(readRaw(e.path), out) : out;
};

const headerProfile = (path: string): string => {
  const first = readRaw(path).split("\n")[0] ?? "";
  return /^# generated by vlt-lab from profile ([^;]*); do not edit$/.exec(first)?.[1] ?? "";
};

const noteUserconfig = (home: string): void => {
  for (const v of [process.env.npm_config_userconfig, process.env.NPM_CONFIG_USERCONFIG]) {
    if (v !== undefined && v !== "" && v !== join(home, ".npmrc")) {
      log(`note: npm_config_userconfig=${v} is set, so npm, pnpm and yarn read it instead of ${join(home, ".npmrc")}`);
      return;
    }
  }
};

const utcStamp = (): string => new Date().toISOString().replace(/[-:]/g, "").replace(/\.\d+Z$/, "Z");

const backupPath = (path: string): string => {
  for (;;) {
    const b = `${path}.vlt-lab.${utcStamp()}.bak`;
    if (!existsSync(b)) return b;
    Bun.sleepSync(1000);
  }
};

const newestBackup = (path: string): string => {
  const dir = dirname(path);
  const base = basename(path);
  if (!existsSync(dir)) return "";
  const hits = readdirSync(dir)
    .filter((n) => n.startsWith(`${base}.vlt-lab.`) && n.endsWith(".bak"))
    .sort();
  return hits.length === 0 ? "" : join(dir, hits[hits.length - 1] as string);
};

const writeAtomic = (path: string, content: string): void => {
  mkdirSync(dirname(path), { recursive: true });
  const tmp = `${path}.vlt-lab.tmp.${process.pid}`;
  writeFileSync(tmp, content);
  renameSync(tmp, path);
};

const profileNames = (): string[] => Object.keys(doc.profiles);

const doDiff = (es: Entry[], profile: string | undefined): void => {
  const name = pickProfile(doc, profile, process.env).name;
  const dir = mkdtempSync(join(tmpdir(), "vlt-lab-user-config."));
  try {
    for (const e of es) {
      const next = renderEntry(e, profile);
      const exists = existsSync(e.path);
      if (exists && readRaw(e.path) === next) {
        log(`${e.target}: ${e.path} unchanged`);
        continue;
      }
      const tmp = join(dir, "new");
      writeFileSync(tmp, next);
      const old = exists ? e.path : "/dev/null";
      const r = run(["diff", "-u", "--label", old, "--label", `${e.path} (profile ${name})`, old, tmp], { capture: true });
      process.stdout.write(r.stdout);
    }
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
};

const doApply = (es: Entry[], loc: Loc, home: string | undefined, profile: string | undefined): void => {
  const name = pickProfile(doc, profile, process.env).name;
  noteUserconfig(loc.home);
  const applied: string[] = [];
  for (const e of es) {
    const next = renderEntry(e, profile);
    if (existsSync(e.path) && readRaw(e.path) === next) {
      console.log(`${e.target}\tunchanged\t${e.path}`);
      continue;
    }
    mkdirSync(dirname(e.path), { recursive: true });
    if (existsSync(e.path)) {
      const b = backupPath(e.path);
      copyFileSync(e.path, b);
      console.log(`${e.target}\tbackup\t${b}`);
    }
    writeAtomic(e.path, next);
    console.log(`${e.target}\twrote\t${e.path} (profile ${name})`);
    if (!applied.includes(e.target)) applied.push(e.target);
  }
  if (es.some((e) => e.target === "env")) {
    const c = join(loc.config, "vlt-lab");
    console.log(`hint: sh: . '${join(c, "env.sh")}'   nu: source '${join(c, "env.nu")}'`);
  }
  if (applied.length > 0) {
    const h = home !== undefined && home !== "" ? ` --home ${loc.home}` : "";
    console.log(`restore: bun ${join(import.meta.dir, "user-config.ts")} restore --targets ${applied.join(",")}${h}`);
  }
};

/** True when the file is exactly what some profile renders. */
const generated = (e: Entry): boolean => {
  if (e.rt === "vlt-json") {
    const cur = readRaw(e.path);
    return profileNames().some((p) => tryRender("vlt-json", p) === cur);
  }
  return headerProfile(e.path) !== "";
};

const doRestore = (es: Entry[]): void => {
  for (const e of es) {
    const b = newestBackup(e.path);
    if (b !== "") {
      renameSync(b, e.path);
      console.log(`${e.target}\trestored\t${e.path} from ${b}`);
    } else if (existsSync(e.path) && generated(e)) {
      rmSync(e.path, { force: true });
      console.log(`${e.target}\tremoved\t${e.path} (created by vlt-lab, no backup)`);
    } else {
      console.log(`${e.target}\tno-backup\t${e.path}`);
    }
  }
};

const doStatus = (es: Entry[], loc: Loc): void => {
  noteUserconfig(loc.home);
  for (const e of es) {
    let state = "missing";
    let p = "-";
    if (existsSync(e.path)) {
      state = "unmanaged";
      const cur = readRaw(e.path);
      if (e.rt === "vlt-json") {
        for (const cand of profileNames()) {
          const r = tryRender("vlt-json", cand);
          if (r === undefined) continue;
          let merged: string | undefined;
          try {
            merged = mergeVltJson(cur, r);
          } catch {
            break;
          }
          if (merged === cur) {
            state = "managed";
            p = cand;
            break;
          }
        }
      } else {
        const hp = headerProfile(e.path);
        if (hp !== "") {
          p = hp;
          state = "managed";
          const fresh = tryRender(e.rt, hp);
          if (fresh !== undefined && fresh !== cur) state = "drifted";
        }
      }
    }
    console.log(`${e.target}\t${state}\t${p}\t${e.path}`);
  }
};

const main = (argv: string[]): void => {
  const { values, positionals } = parseArgs({
    args: argv,
    options: {
      profile: { type: "string" },
      targets: { type: "string", default: ALL_TARGETS },
      home: { type: "string" },
      help: { type: "boolean", short: "h" },
    },
    allowPositionals: true,
  });
  if (values.help) {
    console.log(USAGE);
    return;
  }
  const command = positionals[0] ?? "diff";
  if (positionals.length > 1 || !["diff", "apply", "restore", "status"].includes(command)) {
    process.stderr.write(`${USAGE}\n`);
    process.exit(2);
  }
  const loc = locations(values.home);
  const es = entries(values.targets, loc);
  if (command === "diff") doDiff(es, values.profile);
  else if (command === "apply") doApply(es, loc, values.home, values.profile);
  else if (command === "restore") doRestore(es);
  else doStatus(es, loc);
};

try {
  main(process.argv.slice(2));
} catch (error) {
  die(error instanceof Error ? error.message : String(error));
}
