#!/usr/bin/env nu
# user-config.nu: apply a registry profile to every client's user-level config.
#
#   nu user-config.nu <diff|apply|restore|status> [--profile NAME]
#                     [--targets npmrc,bunfig,yarnrc,vlt-json,env] [--home DIR]
#
# Same flags and effects as user-config.sh and user-config.ts.

use ../../lib/nu/common.nu *
use ../../lib/nu/registry-profile.nu

const ALL_TARGETS = "npmrc,bunfig,yarnrc,vlt-json,env"
const HERE = path self .

# Paths, computed the way the clients compute them.
def locations [home?: string]: nothing -> record {
  if ($home | is-not-empty) {
    mkdir $home
    let h = $home | path expand
    {home: $h, config: ($h | path join .config), xdg: false}
  } else {
    let h = $env.HOME
    let x = $env.XDG_CONFIG_HOME? | default ""
    if ($x | is-not-empty) { {home: $h, config: $x, xdg: true} } else { {home: $h, config: ($h | path join .config), xdg: false} }
  }
}

def entries [targets: string, loc: record]: nothing -> list<record> {
  # bun 1.4 reads $XDG_CONFIG_HOME/.bunfig.toml when XDG_CONFIG_HOME is set, else $HOME/.bunfig.toml
  let bunfig = if $loc.xdg { $loc.config | path join .bunfig.toml } else { $loc.home | path join .bunfig.toml }
  $targets | split row "," | where {|t| $t != "" } | each {|t|
    match $t {
      npmrc => [{target: npmrc, rt: npmrc, path: ($loc.home | path join .npmrc)}]
      bunfig => [{target: bunfig, rt: bunfig, path: $bunfig}]
      yarnrc => [{target: yarnrc, rt: yarnrc, path: ($loc.home | path join .yarnrc.yml)}]
      vlt-json => [{target: vlt-json, rt: vlt-json, path: ($loc.config | path join vlt vlt.json)}]
      env => [
        {target: env, rt: env-sh, path: ($loc.config | path join vlt-lab env.sh)}
        {target: env, rt: env-nu, path: ($loc.config | path join vlt-lab env.nu)}
      ]
      _ => { error make --unspanned { msg: $"unknown target ($t); expected some of: ($ALL_TARGETS)" } }
    }
  } | flatten
}

def read-raw [path: string]: nothing -> string {
  if ($path | path exists) { open --raw $path | decode utf-8 } else { "" }
}

# vlt.json merge: vlt-lab owns config.registries, config.scoped-registries and
# config.command.build; every other key in the existing file is preserved.
def merge-vlt-json [current: string, rendered: string]: nothing -> string {
  let cur = if ($current | is-empty) { {} } else { $current | from json }
  if ($cur | describe | str starts-with "record") == false { error make --unspanned { msg: "vlt.json is not a JSON object" } }
  let n = $rendered | from json | get config
  let cfg = $cur.config? | default {} | upsert registries $n.registries
  let cfg = if ("scoped-registries" in ($n | columns)) {
    $cfg | upsert scoped-registries ($n | get scoped-registries)
  } else {
    $cfg | reject --optional scoped-registries
  }
  let command = $cfg.command? | default {} | upsert build $n.command.build
  let cfg = $cfg | upsert command $command
  ($cur | upsert config $cfg | to json --indent 2) + "\n"
}

def render-entry [e: record, profile?: string]: nothing -> string {
  let out = registry-profile render $e.rt $profile
  if $e.rt == vlt-json { merge-vlt-json (read-raw $e.path) $out } else { $out }
}

def header-profile [path: string]: nothing -> string {
  if not ($path | path exists) { return "" }
  let first = read-raw $path | lines | get 0? | default ""
  let m = $first | parse --regex '^# generated by vlt-lab from profile (?<p>[^;]*); do not edit$'
  if ($m | is-empty) { "" } else { $m.0.p }
}

def note-userconfig [home: string] {
  for v in [($env.npm_config_userconfig? | default "") ($env.NPM_CONFIG_USERCONFIG? | default "")] {
    if ($v | is-not-empty) and $v != ($home | path join .npmrc) {
      vl-log $"note: npm_config_userconfig=($v) is set, so npm, pnpm and yarn read it instead of ($home | path join .npmrc)"
      return
    }
  }
}

def utc-stamp []: nothing -> string { date now | date to-timezone UTC | format date "%Y%m%dT%H%M%SZ" }

def backup-path [path: string]: nothing -> string {
  mut b = $"($path).vlt-lab.(utc-stamp).bak"
  while ($b | path exists) { sleep 1sec; $b = $"($path).vlt-lab.(utc-stamp).bak" }
  $b
}

def newest-backup [path: string]: nothing -> string {
  let dir = $path | path dirname
  let base = $path | path basename
  if not ($dir | path exists) { return "" }
  let hits = ls --all $dir | get name | each {|n| $n | path basename }
    | where {|n| ($n | str starts-with $"($base).vlt-lab.") and ($n | str ends-with ".bak") }
    | sort
  if ($hits | is-empty) { "" } else { $dir | path join ($hits | last) }
}

def write-atomic [path: string, content: string] {
  mkdir ($path | path dirname)
  let tmp = $"($path).vlt-lab.tmp.($nu.pid)"
  $content | save --raw --force $tmp
  ^mv -f $tmp $path
}

def profile-names []: nothing -> list<string> { registry-profile list | get name }

# Unified diff of current file vs rendered content; prints nothing when equal.
def do-diff [es: list<record>, profile?: string] {
  let name = (registry-profile resolve $profile).name
  let tmp = mktemp --tmpdir vlt-lab-user-config.XXXXXX
  for e in $es {
    let new = render-entry $e $profile
    let exists = $e.path | path exists
    if $exists and (read-raw $e.path) == $new { vl-log $"($e.target): ($e.path) unchanged"; continue }
    $new | save --raw --force $tmp
    let old = if $exists { $e.path } else { "/dev/null" }
    let r = ^diff -u --label $old --label $"($e.path) \(profile ($name)\)" $old $tmp | complete
    print --no-newline $r.stdout
  }
  rm -f $tmp
}

def do-apply [es: list<record>, loc: record, home?: string, profile?: string] {
  let name = (registry-profile resolve $profile).name
  note-userconfig $loc.home
  mut applied = []
  for e in $es {
    let new = render-entry $e $profile
    if ($e.path | path exists) and (read-raw $e.path) == $new {
      print $"($e.target)\tunchanged\t($e.path)"
      continue
    }
    mkdir ($e.path | path dirname)
    if ($e.path | path exists) {
      let b = backup-path $e.path
      ^cp -p $e.path $b
      print $"($e.target)\tbackup\t($b)"
    }
    write-atomic $e.path $new
    print $"($e.target)\twrote\t($e.path) \(profile ($name)\)"
    if $e.target not-in $applied { $applied = $applied | append $e.target }
  }
  if ($es | any {|e| $e.target == env }) {
    let c = $loc.config | path join vlt-lab
    print $"hint: sh: . '($c | path join env.sh)'   nu: source '($c | path join env.nu)'"
  }
  if ($applied | is-not-empty) {
    let h = if ($home | is-not-empty) { $" --home ($loc.home)" } else { "" }
    print $"restore: nu ($HERE | path join user-config.nu) restore --targets ($applied | str join ',')($h)"
  }
}

# True when the file is exactly what some profile renders.
def generated [e: record]: nothing -> bool {
  if $e.rt == vlt-json {
    let cur = read-raw $e.path
    profile-names | any {|p| (try { registry-profile render vlt-json $p } catch { null }) == $cur }
  } else {
    (header-profile $e.path) != ""
  }
}

def do-restore [es: list<record>] {
  for e in $es {
    let b = newest-backup $e.path
    if $b != "" {
      ^mv -f $b $e.path
      print $"($e.target)\trestored\t($e.path) from ($b)"
    } else if ($e.path | path exists) and (generated $e) {
      rm -f $e.path
      print $"($e.target)\tremoved\t($e.path) \(created by vlt-lab, no backup\)"
    } else {
      print $"($e.target)\tno-backup\t($e.path)"
    }
  }
}

def do-status [es: list<record>, loc: record] {
  note-userconfig $loc.home
  for e in $es {
    mut state = "missing"
    mut p = "-"
    if ($e.path | path exists) {
      $state = "unmanaged"
      if $e.rt == vlt-json {
        let cur = read-raw $e.path
        for cand in (profile-names) {
          let merged = try { merge-vlt-json $cur (registry-profile render vlt-json $cand) } catch { null }
          if $merged == $cur { $state = "managed"; $p = $cand; break }
        }
      } else {
        let hp = header-profile $e.path
        if $hp != "" {
          $p = $hp
          $state = "managed"
          let fresh = try { registry-profile render $e.rt $hp } catch { null }
          if $fresh != null and $fresh != (read-raw $e.path) { $state = "drifted" }
        }
      }
    }
    print $"($e.target)\t($state)\t($p)\t($e.path)"
  }
}

# Apply a registry profile to every client's user-level config.
def main [
  command: string = "diff"  # diff | apply | restore | status
  --profile: string         # profile name (default: $VLT_LAB_PROFILE, then the document default)
  --targets: string = "npmrc,bunfig,yarnrc,vlt-json,env"  # comma-separated subset
  --home: string            # treat DIR as HOME; inherited XDG_CONFIG_HOME is ignored
] {
  if $command not-in [diff apply restore status] {
    error make --unspanned { msg: "usage: user-config <diff|apply|restore|status> [--profile NAME] [--targets LIST] [--home DIR]" }
  }
  vl-need diff
  let loc = locations $home
  let es = entries $targets $loc
  match $command {
    diff => (do-diff $es $profile)
    apply => (do-apply $es $loc $home $profile)
    restore => (do-restore $es)
    status => (do-status $es $loc)
  }
}
