#!/bin/sh
# user-config.sh: apply a registry profile to every client's user-level config.
#
#   sh user-config.sh <diff|apply|restore|status> [--profile NAME]
#                     [--targets npmrc,bunfig,yarnrc,vlt-json,env] [--home DIR]
#
# diff (default) changes nothing. apply backs up each file it replaces to
# <file>.vlt-lab.<UTC YYYYmmddTHHMMSSZ>.bak and writes atomically. restore puts
# back the newest backup per target. status reports which files vlt-lab manages.
set -eu

HERE=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
VL_ROOT=$(CDPATH='' cd -- "$HERE/../.." && pwd)
export VL_ROOT
# shellcheck source=../../lib/sh/common.sh
. "$VL_ROOT/lib/sh/common.sh"
export LC_ALL=C

ALL_TARGETS=npmrc,bunfig,yarnrc,vlt-json,env
TAB=$(printf '\t')

usage() {
  cat <<EOF
usage: user-config <diff|apply|restore|status> [--profile NAME] [--targets LIST] [--home DIR]
  --targets   comma-separated subset of: $ALL_TARGETS (default: all)
  --home DIR  treat DIR as HOME; inherited XDG_CONFIG_HOME is ignored (config dir = DIR/.config)
EOF
}

cmd=""; profile=""; targets=$ALL_TARGETS; home=""
while [ $# -gt 0 ]; do
  case $1 in
    --profile) [ $# -ge 2 ] || vl_die "--profile needs a value"; profile=$2; shift 2 ;;
    --profile=*) profile=${1#*=}; shift ;;
    --targets) [ $# -ge 2 ] || vl_die "--targets needs a value"; targets=$2; shift 2 ;;
    --targets=*) targets=${1#*=}; shift ;;
    --home) [ $# -ge 2 ] || vl_die "--home needs a value"; home=$2; shift 2 ;;
    --home=*) home=${1#*=}; shift ;;
    -h|--help) usage; exit 0 ;;
    -*) usage >&2; exit 2 ;;
    *) [ -z "$cmd" ] || { usage >&2; exit 2; }; cmd=$1; shift ;;
  esac
done
cmd=${cmd:-diff}
case $cmd in diff|apply|restore|status) ;; *) usage >&2; exit 2 ;; esac
vl_need jq diff

# Paths, computed the way the clients compute them.
if [ -n "$home" ]; then
  mkdir -p "$home"
  H=$(CDPATH='' cd -- "$home" && pwd); C=$H/.config; xdg=0
else
  H=${HOME:?HOME is not set}
  if [ -n "${XDG_CONFIG_HOME:-}" ]; then C=$XDG_CONFIG_HOME; xdg=1; else C=$H/.config; xdg=0; fi
fi
# bun 1.4 reads $XDG_CONFIG_HOME/.bunfig.toml when XDG_CONFIG_HOME is set, else $HOME/.bunfig.toml
if [ "$xdg" = 1 ]; then BUNFIG=$C/.bunfig.toml; else BUNFIG=$H/.bunfig.toml; fi

TMP=$(mktemp -d "${TMPDIR:-/tmp}/vlt-lab-user-config.XXXXXX")
trap 'rm -rf "$TMP"' EXIT
trap 'exit 130' INT TERM
trap 'exit 129' HUP
trap 'exit 141' PIPE

# entries: one line per file, "<target>\t<renderer target>\t<path>"
: > "$TMP/entries"
old_ifs=$IFS; IFS=,
for t in $targets; do
  IFS=$old_ifs
  case $t in
    npmrc) printf 'npmrc\tnpmrc\t%s\n' "$H/.npmrc" ;;
    bunfig) printf 'bunfig\tbunfig\t%s\n' "$BUNFIG" ;;
    yarnrc) printf 'yarnrc\tyarnrc\t%s\n' "$H/.yarnrc.yml" ;;
    vlt-json) printf 'vlt-json\tvlt-json\t%s\n' "$C/vlt/vlt.json" ;;
    env) printf 'env\tenv-sh\t%s\nenv\tenv-nu\t%s\n' "$C/vlt-lab/env.sh" "$C/vlt-lab/env.nu" ;;
    '') ;;
    *) vl_die "unknown target $t; expected some of: $ALL_TARGETS" ;;
  esac >> "$TMP/entries"
done
IFS=$old_ifs

# vlt.json merge: vlt-lab owns config.registries, config.scoped-registries and
# config.command.build; every other key in the existing file is preserved.
MERGE_JQ='
  $r[0].config as $n
  | if type != "object" then error("vlt.json is not a JSON object") else . end
  | .config = (.config // {})
  | .config.registries = $n.registries
  | if ($n | has("scoped-registries")) then .config["scoped-registries"] = $n["scoped-registries"]
    else del(.config["scoped-registries"]) end
  | .config.command = (.config.command // {})
  | .config.command.build = $n.command.build'

# merge_vlt_json <current file> <rendered file>: print the merged document
merge_vlt_json() {
  if [ -s "$1" ]; then jq --slurpfile r "$2" "$MERGE_JQ" "$1"
  else printf '{}' | jq --slurpfile r "$2" "$MERGE_JQ"; fi
}

# render_entry <renderer target> <path> <out> [profile]: what the file should contain
render_entry() {
  if [ "$1" = vlt-json ]; then
    vl_profile render vlt-json "${4-$profile}" > "$TMP/rendered.json" || return 1
    merge_vlt_json "$2" "$TMP/rendered.json" > "$3"
  else
    vl_profile render "$1" "${4-$profile}" > "$3"
  fi
}

# header_profile <file>: profile name from the vlt-lab header, empty when absent
header_profile() {
  sed -n '1s/^# generated by vlt-lab from profile \([^;]*\); do not edit$/\1/p' "$1" 2>/dev/null
}

profile_name() {
  vl_profile render env-sh "$profile" > "$TMP/name" || exit 1
  header_profile "$TMP/name"
}

note_userconfig() {
  for _v in "${npm_config_userconfig:-}" "${NPM_CONFIG_USERCONFIG:-}"; do
    if [ -n "$_v" ] && [ "$_v" != "$H/.npmrc" ]; then
      vl_log "note: npm_config_userconfig=$_v is set, so npm, pnpm and yarn read it instead of $H/.npmrc"
      return 0
    fi
  done
}

backup_path() {
  while :; do
    _b="$1.vlt-lab.$(date -u +%Y%m%dT%H%M%SZ).bak"
    [ -e "$_b" ] || { printf '%s\n' "$_b"; return 0; }
    sleep 1
  done
}

newest_backup() {
  _newest=""
  for _f in "$1".vlt-lab.*.bak; do [ -e "$_f" ] && _newest=$_f; done
  printf '%s' "$_newest"
}

do_diff() {
  name=$(profile_name)
  while IFS=$TAB read -r target rt path <&3; do
    render_entry "$rt" "$path" "$TMP/new" || exit 1
    if [ -f "$path" ]; then old=$path; old_label=$path; else old=/dev/null; old_label=/dev/null; fi
    if cmp -s "$old" "$TMP/new"; then vl_log "$target: $path unchanged"; continue; fi
    diff -u --label "$old_label" --label "$path (profile $name)" "$old" "$TMP/new" || true
  done 3< "$TMP/entries"
}

do_apply() {
  name=$(profile_name)
  note_userconfig
  applied=""
  while IFS=$TAB read -r target rt path <&3; do
    render_entry "$rt" "$path" "$TMP/new" || exit 1
    if [ -f "$path" ] && cmp -s "$path" "$TMP/new"; then
      printf '%s\tunchanged\t%s\n' "$target" "$path"; continue
    fi
    mkdir -p "$(dirname -- "$path")"
    if [ -e "$path" ]; then
      b=$(backup_path "$path")
      cp -p "$path" "$b"
      printf '%s\tbackup\t%s\n' "$target" "$b"
    fi
    cp "$TMP/new" "$path.vlt-lab.tmp.$$"
    mv -f "$path.vlt-lab.tmp.$$" "$path"
    printf '%s\twrote\t%s (profile %s)\n' "$target" "$path" "$name"
    case ",$applied," in *",$target,"*) ;; *) applied=${applied:+$applied,}$target ;; esac
  done 3< "$TMP/entries"
  if grep -q "^env$TAB" "$TMP/entries"; then
    printf "hint: sh: . '%s'   nu: source '%s'\n" "$C/vlt-lab/env.sh" "$C/vlt-lab/env.nu"
  fi
  if [ -n "$applied" ]; then
    printf 'restore: sh %s restore --targets %s%s\n' "$HERE/user-config.sh" "$applied" "${home:+ --home $H}"
  fi
}

# generated <renderer target> <path>: true when the file is exactly what some profile renders
generated() {
  if [ "$1" = vlt-json ]; then
    for p in $(vl_profile list | cut -f1); do
      vl_profile render vlt-json "$p" > "$TMP/pure" 2>/dev/null || continue
      cmp -s "$2" "$TMP/pure" && return 0
    done
    return 1
  fi
  [ -n "$(header_profile "$2")" ]
}

do_restore() {
  while IFS=$TAB read -r target rt path <&3; do
    b=$(newest_backup "$path")
    if [ -n "$b" ]; then
      mv -f "$b" "$path"
      printf '%s\trestored\t%s from %s\n' "$target" "$path" "$b"
    elif [ -f "$path" ] && generated "$rt" "$path"; then
      rm -f "$path"
      printf '%s\tremoved\t%s (created by vlt-lab, no backup)\n' "$target" "$path"
    else
      printf '%s\tno-backup\t%s\n' "$target" "$path"
    fi
  done 3< "$TMP/entries"
}

do_status() {
  note_userconfig
  while IFS=$TAB read -r target rt path <&3; do
    state=missing; p=-
    if [ -f "$path" ]; then
      state=unmanaged
      if [ "$rt" = vlt-json ]; then
        for cand in $(vl_profile list | cut -f1); do
          vl_profile render vlt-json "$cand" > "$TMP/rendered.json" 2>/dev/null || continue
          merge_vlt_json "$path" "$TMP/rendered.json" > "$TMP/merged" 2>/dev/null || break
          if cmp -s "$path" "$TMP/merged"; then state=managed; p=$cand; break; fi
        done
      else
        hp=$(header_profile "$path")
        if [ -n "$hp" ]; then
          p=$hp; state=managed
          if vl_profile render "$rt" "$hp" > "$TMP/new" 2>/dev/null && ! cmp -s "$path" "$TMP/new"; then
            state=drifted
          fi
        fi
      fi
    fi
    printf '%s\t%s\t%s\t%s\n' "$target" "$state" "$p" "$path"
  done 3< "$TMP/entries"
}

case $cmd in
  diff) do_diff ;;
  apply) do_apply ;;
  restore) do_restore ;;
  status) do_status ;;
esac
