#!/bin/sh
# vlt-install-any.sh: install any JS project with vlt (no lifecycle scripts), gate the
# installed graph with `vlt query`, then build only what the build selector allows.
#
#   sh vlt-install-any.sh [options] <project-dir>
#   sh vlt-install-any.sh phase <detect|fetch|gate|build|report> --state DIR [options] <project-dir>
#
# Each phase runs as its own process and talks to the others only through JSON files in
# the state directory (see README.md, "Phase contract").
set -eu

SELF=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)/$(basename -- "$0")
SELF_DIR=$(dirname -- "$SELF")
VL_ROOT=$(CDPATH= cd -- "$SELF_DIR/../.." && pwd -P)
. "$VL_ROOT/lib/sh/common.sh"

IMPL=sh
DEFAULT_BUILD=':scripts:not(:built):not(:malware)'
NO_SCRIPTS=':not(*)'
LOCKFILES="npm-shrinkwrap.json package-lock.json pnpm-lock.yaml yarn.lock bun.lock bun.lockb vlt-lock.json"

usage() {
  cat >&2 <<'EOF'
usage: vlt-install-any.sh [options] <project-dir>
       vlt-install-any.sh phase <detect|fetch|gate|build|report> --state DIR [options] <project-dir>

options:
  --profile NAME            registry profile (default: $VLT_LAB_PROFILE, then the document default)
  --gate FILE               gate rules (default: gate.default.json next to this script)
  --build SELECTOR          what `vlt build` may build (default: :scripts:not(:built):not(:malware))
  --no-build                skip the build; report what is pending instead
  --report FILE             also write the report JSON to FILE (always printed on stdout)
  --keep-foreign-lockfile   accepted for clarity; foreign lockfiles are never modified
  --state DIR               phase state directory (default: a new dir under <repo>/.tmp)
  --pin-root                write an empty vlt.json into the project when vlt would otherwise
                            treat a parent directory as the project root

exit codes: 0 ok, 1 internal error, 2 usage or refused, 3 gate blocked, 4 fetch failed, 5 build failed
EOF
  exit 2
}

now_ms() { date +%s%3N; }
sha256_of() { sha256sum "$1" | cut -d' ' -f1; }

PHASE=""; PROFILE=""; GATE=""; BUILD_SEL=$DEFAULT_BUILD; NO_BUILD=0; REPORT=""; STATE=""; PIN_ROOT=0; PROJECT=""
if [ "${1:-}" = phase ]; then
  [ $# -ge 2 ] || usage
  PHASE=$2; shift 2
  case $PHASE in detect|fetch|gate|build|report) ;; *) vl_log "unknown phase: $PHASE"; usage ;; esac
fi
while [ $# -gt 0 ]; do
  case $1 in
    --profile) [ $# -ge 2 ] || usage; PROFILE=$2; shift 2 ;;
    --profile=*) PROFILE=${1#*=}; shift ;;
    --gate) [ $# -ge 2 ] || usage; GATE=$2; shift 2 ;;
    --gate=*) GATE=${1#*=}; shift ;;
    --build) [ $# -ge 2 ] || usage; BUILD_SEL=$2; shift 2 ;;
    --build=*) BUILD_SEL=${1#*=}; shift ;;
    --no-build) NO_BUILD=1; shift ;;
    --report) [ $# -ge 2 ] || usage; REPORT=$2; shift 2 ;;
    --report=*) REPORT=${1#*=}; shift ;;
    --state) [ $# -ge 2 ] || usage; STATE=$2; shift 2 ;;
    --state=*) STATE=${1#*=}; shift ;;
    --keep-foreign-lockfile) shift ;;
    --pin-root) PIN_ROOT=1; shift ;;
    -h|--help) usage ;;
    -*) vl_log "unknown option: $1"; usage ;;
    *) [ -z "$PROJECT" ] || usage; PROJECT=$1; shift ;;
  esac
done
[ -n "$PROJECT" ] || usage
SRC=$(CDPATH= cd -- "$PROJECT" 2>/dev/null && pwd -P) || { vl_log "not a directory: $PROJECT"; exit 2; }
[ -n "$GATE" ] || GATE=$SELF_DIR/gate.default.json
vl_need jq vlt sha256sum

# load_profile: export the profile's registry env (VLT_REGISTRY, VLT_REGISTRIES, ...) via the renderer
load_profile() {
  _envsh=$(vl_profile render env-sh ${PROFILE:+"$PROFILE"}) || { vl_log "cannot render registry profile ${PROFILE:-<default>}"; exit 2; }
  PROFILE_NAME=$(printf '%s\n' "$_envsh" | sed -n '1s/^# generated by vlt-lab from profile \(.*\); do not edit$/\1/p')
  eval "$_envsh"
}

# query_matches <selector> <out-file>: run `vlt query --view=json` in the project, write
# [{id,name,version}] sorted by id; returns vlt's exit code (output file holds the error otherwise)
query_matches() {
  (cd "$SRC" && vlt query "$1" --view=json) >"$2.raw" 2>"$2.err" && _q=0 || _q=$?
  if [ $_q -eq 0 ] && jq -e 'type == "array"' "$2.raw" >/dev/null 2>&1; then
    jq '[.[] | .to | {id, name, version}] | unique_by(.id)' "$2.raw" >"$2"
  else
    [ $_q -ne 0 ] || _q=1
  fi
  rm -f "$2.raw"
  return $_q
}

# ---------------------------------------------------------------- detect
phase_detect() {
  t0=$(now_ms)
  W=$STATE/.detect.warnings.jsonl; L=$STATE/.detect.lockfiles.jsonl; WS=$STATE/.detect.workspaces.jsonl
  : >"$W"; : >"$L"; : >"$WS"
  warn() { jq -nc --arg c "$1" --arg m "$2" '{code: $c, message: $m}' >>"$W"; vl_log "warning: $2"; }
  pj=$SRC/package.json
  if [ ! -f "$pj" ] || ! jq -e 'type == "object"' "$pj" >/dev/null 2>&1; then
    jq -n --arg s "$SRC" --argjson d $(($(now_ms) - t0)) \
      '{phase: "detect", exit: 2, durationMs: $d, source: $s, error: "no readable package.json"}' >"$STATE/detect.json"
    vl_log "no readable package.json in $SRC"; return 2
  fi

  for f in $LOCKFILES; do
    [ -f "$SRC/$f" ] || continue
    case $f in
      npm-shrinkwrap.json|package-lock.json) kind=npm ;;
      pnpm-lock.yaml) kind=pnpm ;;
      yarn.lock) if grep -q '^__metadata:' "$SRC/$f"; then kind=yarn-berry; else kind=yarn-classic; fi ;;
      bun.lock|bun.lockb) kind=bun ;;
      vlt-lock.json) kind=vlt ;;
    esac
    jq -nc --arg f "$f" --arg k "$kind" --arg s "$(sha256_of "$SRC/$f")" \
      '{file: $f, kind: $k, foreign: ($k != "vlt"), sha256: $s}' >>"$L"
    [ "$kind" = vlt ] || warn foreign-lockfile-not-read "$f is not read by vlt; vlt resolves versions fresh from package.json ranges and leaves $f untouched"
  done
  nforeign=$(jq -s '[.[] | select(.foreign)] | length' "$L")
  [ "$nforeign" -le 1 ] || warn multiple-lockfiles "$nforeign foreign lockfiles found; the packageManager field or the first lockfile decides the detected manager"

  pmf=$(jq -r '.packageManager // "" | strings' "$pj")
  pm_from_field=""
  if [ -n "$pmf" ]; then
    pm_name=${pmf%%@*}; pm_ver=${pmf#*@}; pm_ver=${pm_ver%%+*}
    [ "$pm_ver" != "$pmf" ] || pm_ver=""
    case $pm_name in
      yarn) case ${pm_ver%%.*} in 0|1|"") pm_from_field=yarn-classic ;; *) pm_from_field=yarn-berry ;; esac ;;
      *) pm_from_field=$pm_name ;;
    esac
    pm_json=$(jq -nc --arg f "$pmf" --arg n "$pm_name" --arg v "$pm_ver" '{field: $f, name: $n, version: (if $v == "" then null else $v end)}')
  else
    pm_json=null
  fi
  first_kind=$(jq -rs '([.[] | select(.foreign)] + [.[] | select(.foreign | not)]) | (.[0].kind // "")' "$L")
  detected=${pm_from_field:-${first_kind:-unknown}}
  if [ -n "$pm_from_field" ]; then
    jq -r --arg d "$pm_from_field" 'select(.foreign and .kind != $d) | .file' "$L" | while IFS= read -r f; do
      warn packagemanager-mismatch "packageManager says $pm_from_field but $f belongs to another manager"
    done
  fi

  # workspaces: package.json, vlt.json (both read by vlt), pnpm-workspace.yaml (not read)
  if jq -e '.workspaces != null' "$pj" >/dev/null; then
    jq -c '{source: "package.json", patterns: ((.workspaces | if type == "object" then .packages else . end) // [] | if type == "array" then . else [.] end), readByVlt: true}' "$pj" >>"$WS"
  fi
  if [ -f "$SRC/vlt.json" ] && jq -e '.workspaces != null' "$SRC/vlt.json" >/dev/null 2>&1; then
    jq -c '{source: "vlt.json", patterns: (.workspaces | if type == "array" then . elif type == "string" then [.] elif type == "object" then [.[] | if type == "array" then .[] else . end] else [] end), readByVlt: true}' "$SRC/vlt.json" >>"$WS"
  fi
  if [ -f "$SRC/pnpm-workspace.yaml" ]; then
    awk '
      /^packages:/ { inpk = 1; next }
      inpk && /^[^[:space:]#]/ { inpk = 0 }
      inpk && /^[[:space:]]+-[[:space:]]*/ {
        s = $0; sub(/^[[:space:]]+-[[:space:]]*/, "", s); sub(/[[:space:]]+#.*$/, "", s); sub(/[[:space:]]+$/, "", s)
        if (s ~ /^".*"$/ || s ~ /^\047.*\047$/) s = substr(s, 2, length(s) - 2)
        print s
      }' "$SRC/pnpm-workspace.yaml" | jq -Rsc '{source: "pnpm-workspace.yaml", patterns: (split("\n") | map(select(. != ""))), readByVlt: false}' >>"$WS"
    warn pnpm-workspace-ignored "pnpm-workspace.yaml is not read by vlt; its workspace packages are not installed (move the globs to vlt.json \"workspaces\")"
  fi

  # .npmrc: vlt ignores it; list registry routing lines only, never auth values
  if [ -f "$SRC/.npmrc" ]; then
    reglines=$(grep -E '^[[:space:]]*(@[^:=[:space:]]+:)?registry[[:space:]]*=' "$SRC/.npmrc" \
      | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e 's#://[^/@]*@#://***@#' | jq -Rsc 'split("\n") | map(select(. != ""))')
    authn=$(grep -cE '(_authToken|_auth|_password|username|certfile|keyfile)[[:space:]]*=' "$SRC/.npmrc" || true)
    npmrc_json=$(jq -nc --argjson r "$reglines" --argjson a "$authn" '{present: true, registryLines: $r, authLines: $a}')
    warn npmrc-ignored ".npmrc is not read by vlt ($(printf '%s' "$reglines" | jq length) registry lines, $authn auth lines, values not shown); registries come from the vlt-lab profile instead"
  else
    npmrc_json='{"present":false,"registryLines":[],"authLines":0}'
  fi

  # where vlt will put node_modules: it walks up to the topmost package.json below .git or $HOME
  loc=$(cd "$SRC" && vlt config location --config=project 2>/dev/null | jq -r 'strings') || loc=""
  if [ -n "$loc" ]; then
    vlt_root=$(dirname -- "$loc")
    [ "$vlt_root" = "$SRC" ] || warn vlt-root-escape "vlt would treat $vlt_root as the project root, not $SRC; fetch refuses unless --pin-root"
    vlt_root_json=$(jq -nc --arg r "$vlt_root" '$r')
  else
    vlt_root_json=null
    warn vlt-root-unknown "could not ask vlt for the project root"
  fi
  [ -f "$SRC/vlt-lock.json" ] && use_ci=true || use_ci=false

  jq -n --arg s "$SRC" --arg det "$detected" --argjson pm "$pm_json" --argjson npmrc "$npmrc_json" \
    --argjson root "$vlt_root_json" --argjson ci "$use_ci" --argjson d $(($(now_ms) - t0)) \
    --slurpfile lf "$L" --slurpfile ws "$WS" --slurpfile w "$W" \
    '{phase: "detect", exit: 0, durationMs: $d, source: $s, detected: $det, packageManager: $pm,
      lockfiles: $lf, workspaces: $ws, npmrc: $npmrc, vltRoot: $root, useCi: $ci, warnings: $w}' >"$STATE/detect.json"
  rm -f "$W" "$L" "$WS"
  vl_log "detect: $detected ($(jq -r '[.lockfiles[].file] | join(", ") | if . == "" then "no lockfile" else . end' "$STATE/detect.json"))"
}

# ---------------------------------------------------------------- fetch
phase_fetch() {
  t0=$(now_ms)
  [ -f "$STATE/detect.json" ] || { vl_log "fetch needs detect.json in $STATE"; return 2; }
  load_profile
  use_ci=$(jq -r '.useCi' "$STATE/detect.json")
  root=$(jq -r '.vltRoot // ""' "$STATE/detect.json")
  pinned=false
  fail_fetch() {
    jq -n --argjson e "$1" --arg err "$2" --arg p "$PROFILE_NAME" --arg r "${VLT_REGISTRY:-}" --argjson d $(($(now_ms) - t0)) \
      '{phase: "fetch", exit: $e, durationMs: $d, profile: $p, registry: $r, command: null, mode: null, vltExit: null,
        added: null, removed: null, changed: null, buildQueue: [], pinnedRoot: false, error: $err}' >"$STATE/fetch.json"
    vl_log "fetch: $2"
  }
  if [ -n "$root" ] && [ "$root" != "$SRC" ]; then
    if [ $PIN_ROOT -eq 1 ]; then
      printf '{}\n' >"$SRC/vlt.json"; pinned=true
      vl_log "pinned the vlt project root with an empty $SRC/vlt.json"
    else
      fail_fetch 2 "vlt would install into $root instead of $SRC; rerun with --pin-root to pin the root"
      return 2
    fi
  fi
  if [ "$use_ci" = true ]; then mode=ci; else mode=install; fi
  vl_log "fetch: vlt $mode --allow-scripts='$NO_SCRIPTS' (profile $PROFILE_NAME)"
  (cd "$SRC" && vlt "$mode" --allow-scripts="$NO_SCRIPTS") >"$STATE/fetch.stdout.json" 2>"$STATE/fetch.stderr.log" && rc=0 || rc=$?
  if [ $rc -ne 0 ]; then
    fail_fetch 4 "vlt $mode exited $rc; see fetch.stderr.log"
    jq '.vltExit = $rc | .mode = $m' --argjson rc $rc --arg m "$mode" "$STATE/fetch.json" >"$STATE/fetch.json.tmp" && mv "$STATE/fetch.json.tmp" "$STATE/fetch.json"
    return 4
  fi
  if [ "$mode" = install ]; then
    summary=$(jq -c '{added, removed, changed, buildQueue: (.buildQueue // []), source: "vlt-output"}' "$STATE/fetch.stdout.json")
  else
    # `vlt ci` prints the lockfile, not an install summary: derive the queue from the graph
    query_matches ':scripts:not(:built)' "$STATE/.fetch.queue.json" || true
    summary=$(jq -c --slurpfile lock "$STATE/fetch.stdout.json" \
      '{added: ($lock[0].nodes | length), removed: null, changed: null, buildQueue: map(.id), source: "query"}' "$STATE/.fetch.queue.json" 2>/dev/null \
      || printf '{"added":null,"removed":null,"changed":null,"buildQueue":[],"source":"query"}')
    rm -f "$STATE/.fetch.queue.json" "$STATE/.fetch.queue.json.err"
  fi
  jq -n --argjson s "$summary" --arg p "$PROFILE_NAME" --arg r "${VLT_REGISTRY:-}" --arg m "$mode" --arg as "$NO_SCRIPTS" \
    --argjson pin "$pinned" --argjson d $(($(now_ms) - t0)) \
    '{phase: "fetch", exit: 0, durationMs: $d, profile: $p, registry: $r, command: ["vlt", $m, "--allow-scripts=\($as)"],
      mode: $m, vltExit: 0, added: $s.added, removed: $s.removed, changed: $s.changed, buildQueue: $s.buildQueue,
      buildQueueSource: $s.source, pinnedRoot: $pin, error: null}' >"$STATE/fetch.json"
  vl_log "fetch: ok, build queue: $(jq -r '.buildQueue | if length == 0 then "empty" else join(", ") end' "$STATE/fetch.json")"
}

# ---------------------------------------------------------------- gate
phase_gate() {
  t0=$(now_ms)
  fail_gate() {
    jq -n --arg f "$GATE" --arg err "$1" --argjson d $(($(now_ms) - t0)) \
      '{phase: "gate", exit: 2, durationMs: $d, file: $f, blocked: true, rules: [], error: $err}' >"$STATE/gate.json"
    vl_log "gate: $1"
  }
  [ -f "$STATE/fetch.json" ] && [ "$(jq -r .exit "$STATE/fetch.json")" = 0 ] || { fail_gate "gate needs a successful fetch.json in $STATE"; return 2; }
  if ! jq -e '(.rules | type == "array") and all(.rules[]; (.selector | type == "string") and ((.severity // "warn") | IN("block", "warn", "info")))' "$GATE" >/dev/null 2>&1; then
    fail_gate "invalid gate file $GATE (need {\"rules\": [{\"selector\", \"expect\", \"severity\": block|warn|info}]})"; return 2
  fi
  load_profile
  R=$STATE/.gate.rules.jsonl; : >"$R"
  n=$(jq '.rules | length' "$GATE"); i=0
  while [ $i -lt "$n" ]; do
    rule=$(jq -c --argjson i $i '.rules[$i] | {name: (.name // .selector), selector, expect: ((.expect // "0") | tostring), severity: (.severity // "warn")}' "$GATE")
    sel=$(printf '%s' "$rule" | jq -r .selector); exp=$(printf '%s' "$rule" | jq -r .expect)
    M=$STATE/.gate.match.json
    if query_matches "$sel" "$M"; then
      (cd "$SRC" && vlt query "$sel" --expect-results="$exp" --view=json) >/dev/null 2>&1 && erc=0 || erc=$?
      [ $erc -eq 0 ] && status=pass || status=fail
      jq -c --argjson r "$rule" --arg st "$status" --argjson erc $erc \
        '$r + {status: $st, count: length, matches: ., expectExit: $erc, error: null}' "$M" >>"$R"
    else
      err=$(grep -m1 -v '^[[:space:]]*$' "$M.err" 2>/dev/null || printf 'vlt query failed')
      jq -nc --argjson r "$rule" --arg e "$err" '$r + {status: "error", count: null, matches: [], expectExit: null, error: $e}' >>"$R"
    fi
    rm -f "$M" "$M.err"
    jq -r '"gate \(.name) [\(.severity)] \(.selector) expect \(.expect): \(.status) (\(.count // "?") matches)"' <<EOF >&2
$(tail -n 1 "$R")
EOF
    i=$((i + 1))
  done
  blocked=$(jq -s 'any(.[]; .severity == "block" and .status != "pass")' "$R")
  [ "$blocked" = true ] && code=3 || code=0
  jq -n --arg f "$GATE" --argjson b "$blocked" --argjson e $code --argjson d $(($(now_ms) - t0)) --slurpfile r "$R" \
    '{phase: "gate", exit: $e, durationMs: $d, file: $f, blocked: $b, rules: $r, error: null}' >"$STATE/gate.json"
  rm -f "$R"
  [ "$blocked" = false ] || vl_log "gate: BLOCKED by $(jq -r '[.rules[] | select(.severity == "block" and .status != "pass") | .name] | join(", ")' "$STATE/gate.json")"
  return $code
}

# ---------------------------------------------------------------- build
phase_build() {
  t0=$(now_ms)
  write_build() { # <exit> <skipped> <reason|""> <built-file|""> <failed-file|"">
    pend=$STATE/.build.pending.json
    if [ -f "$STATE/fetch.json" ] && [ "$(jq -r .exit "$STATE/fetch.json")" = 0 ]; then
      query_matches ':scripts:not(:built)' "$pend" || printf 'null' >"$pend"
      rm -f "$pend.err"
    else printf 'null' >"$pend"; fi
    jq -n --argjson e "$1" --argjson sk "$2" --arg why "$3" --arg t "$BUILD_SEL" --argjson d $(($(now_ms) - t0)) \
      --slurpfile b "${4:-/dev/null}" --slurpfile f "${5:-/dev/null}" --slurpfile p "$pend" \
      '{phase: "build", exit: $e, durationMs: $d, skipped: $sk, skipReason: (if $why == "" then null else $why end),
        target: $t, built: ($b[0] // []), failed: ($f[0] // []), pending: $p[0]}' >"$STATE/build.json"
    rm -f "$pend"
  }
  if [ ! -f "$STATE/gate.json" ]; then write_build 3 true gate-missing; vl_log "build: refused, no gate.json in $STATE"; return 3; fi
  load_profile
  if [ "$(jq -r .blocked "$STATE/gate.json")" != false ]; then
    write_build 3 true gate-blocked; vl_log "build: refused, the gate blocked this install"; return 3
  fi
  if [ $NO_BUILD -eq 1 ]; then
    write_build 0 true no-build
    vl_log "build: skipped (--no-build), pending: $(jq -r '.pending // [] | map("\(.name)@\(.version)") | if length == 0 then "none" else join(", ") end' "$STATE/build.json")"
    return 0
  fi
  vl_log "build: vlt build --target '$BUILD_SEL'"
  (cd "$SRC" && vlt build --target "$BUILD_SEL") >"$STATE/build.stdout.json" 2>"$STATE/build.stderr.log" && rc=0 || rc=$?
  B=$STATE/.build.built.json; F=$STATE/.build.failed.json
  jq '[(.success // [])[] | {id, name, version}]' "$STATE/build.stdout.json" >"$B" 2>/dev/null || printf '[]' >"$B"
  jq '[(.failure // [])[] | if type == "object" then {id, name, version} else {id: tostring, name: null, version: null} end]' "$STATE/build.stdout.json" >"$F" 2>/dev/null || printf '[]' >"$F"
  if [ $rc -eq 0 ] && [ "$(jq length "$F")" = 0 ]; then code=0; else code=5; fi
  write_build $code false "" "$B" "$F"
  rm -f "$B" "$F"
  vl_log "build: built $(jq -r '.built | map("\(.name)@\(.version)") | if length == 0 then "nothing" else join(", ") end' "$STATE/build.json"), pending: $(jq -r '.pending // [] | map("\(.name)@\(.version)") | if length == 0 then "none" else join(", ") end' "$STATE/build.json")"
  return $code
}

# ---------------------------------------------------------------- report
phase_report() {
  t0=$(now_ms)
  rd() { if [ -f "$STATE/$1.json" ]; then cat "$STATE/$1.json"; else printf 'null'; fi; }
  # recompute lockfile checksums after the run
  A=$STATE/.report.after.jsonl; : >"$A"
  for f in $LOCKFILES; do
    [ -f "$SRC/$f" ] && jq -nc --arg f "$f" --arg s "$(sha256_of "$SRC/$f")" '{($f): $s}' >>"$A"
  done
  vv=$(vlt --version 2>/dev/null | head -n 1) || vv=""
  [ -f "$SRC/vlt-lock.json" ] && vlock=true || vlock=false
  out=$(jq -n --arg impl "$IMPL" --arg src "$SRC" --arg vv "$vv" --arg now "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
    --argjson vlock "$vlock" --argjson t0 "$t0" --argjson tn "$(now_ms)" \
    --argjson detect "$(rd detect)" --argjson fetch "$(rd fetch)" --argjson gate "$(rd gate)" --argjson build "$(rd build)" \
    --slurpfile after "$A" '
    ($after | add // {}) as $aft
    | ($detect.lockfiles // [] | map(. as $l | {file, kind, foreign, sha256Before: .sha256, sha256After: ($aft[$l.file] // null)}
        | .unchanged = (.sha256Before == .sha256After))) as $locks
    | def ph($p): if $p == null then null else {exit: $p.exit, durationMs: $p.durationMs} end;
    ([$detect, $fetch, $gate, $build] | map(select(. != null) | .exit) | map(select(. != 0)) | .[0] // 0) as $exit
    | {
        schemaVersion: 1, tool: "vlt-install-any", implementation: $impl, generatedAt: $now,
        vltVersion: (if $vv == "" then null else $vv end), source: $src,
        profile: (if $fetch == null then null else {name: $fetch.profile, registry: $fetch.registry} end),
        detected: ($detect.detected // null), packageManager: ($detect.packageManager // null),
        lockfiles: $locks,
        foreignLockfilesUnchanged: ($locks | map(select(.foreign)) | all(.unchanged)),
        vltLockfile: $vlock, keepForeignLockfile: true,
        workspaces: ($detect.workspaces // []), npmrc: ($detect.npmrc // null), vltRoot: ($detect.vltRoot // null),
        warnings: (($detect.warnings // []) + ($gate.rules // [] | map(select(.severity == "warn" and .status != "pass")
          | {code: "gate-\(.name)", message: "gate rule \(.name) (\(.selector)) expected \(.expect), got \(.count // "an error")"}))),
        phases: {detect: ph($detect), fetch: ph($fetch), gate: ph($gate), build: ph($build), report: {exit: 0, durationMs: ($tn - $t0)}},
        fetch: (if $fetch == null then null else $fetch | {mode, command, added, removed, changed, buildQueue, pinnedRoot, error} end),
        gate: (if $gate == null then null else $gate | {file, blocked, rules, error} end),
        build: (if $build == null then null else $build | {skipped, skipReason, target, built, failed, pending} end),
        exit: $exit
      }')
  rm -f "$A"
  printf '%s\n' "$out" >"$STATE/report.json"
  [ -z "$REPORT" ] || { mkdir -p "$(dirname -- "$REPORT")"; printf '%s\n' "$out" >"$REPORT"; }
  printf '%s\n' "$out"
}

run_phase() {
  mkdir -p "$STATE"
  STATE=$(CDPATH= cd -- "$STATE" && pwd -P)
  case $1 in
    detect) phase_detect ;; fetch) phase_fetch ;; gate) phase_gate ;; build) phase_build ;; report) phase_report ;;
  esac
}

if [ -n "$PHASE" ]; then
  [ -n "$STATE" ] || { vl_log "phase mode needs --state DIR"; usage; }
  run_phase "$PHASE" && exit 0 || exit $?
fi

# ---------------------------------------------------------------- orchestrator
[ -n "$STATE" ] || STATE=$(vl_scratch vlt-install-any)
vl_log "state: $STATE"
set -- --state "$STATE" --gate "$GATE" --build "$BUILD_SEL" ${PROFILE:+--profile "$PROFILE"}
[ $NO_BUILD -eq 0 ] || set -- "$@" --no-build
[ $PIN_ROOT -eq 0 ] || set -- "$@" --pin-root
phase_cmd() { _p=$1; shift; sh "$SELF" phase "$_p" "$@" "$SRC"; }
phase_cmd detect "$@" && rc=0 || rc=$?
if [ $rc -eq 0 ]; then
  phase_cmd fetch "$@" && rc=0 || rc=$?
  if [ $rc -eq 0 ]; then
    phase_cmd gate "$@" && rc=0 || rc=$?
    if [ $rc -eq 0 ] || [ $rc -eq 3 ]; then
      phase_cmd build "$@" || true
    fi
  fi
fi
phase_cmd report "$@" ${REPORT:+--report "$REPORT"} >"$STATE/.report.stdout" || { cat "$STATE/.report.stdout"; exit 1; }
cat "$STATE/.report.stdout"; rm -f "$STATE/.report.stdout"
exit "$(jq -r .exit "$STATE/report.json")"
