#!/bin/sh
# registry-profile.sh: POSIX sh + jq port of packages/registry-profile (TypeScript reference).
# Output must stay byte-identical to the reference; `just conformance` checks it.
#
#   lib/sh/registry-profile.sh render npmrc vlt-hosted
#   eval "$(lib/sh/registry-profile.sh render env-sh)"
set -eu

LIB_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
FILE=${VLT_LAB_PROFILES:-$LIB_DIR/../../config/registry.profiles.json}
TARGETS="npmrc bunfig yarnrc vlt-json env-sh env-nu hosts"

die() { printf 'registry-profile: %s\n' "$*" >&2; exit 1; }
command -v jq >/dev/null 2>&1 || die "jq is required"

# Resolve a profile to JSON: placeholders substituted, hosts derived. jq reads $ENV directly.
resolve() {
  out=$(jq -e --arg want "${1:-}" '
    def sub($name):
      gsub("\\{env:(?<k>[A-Za-z_][A-Za-z0-9_]*)\\}";
        (($ENV[.k] // "") as $v
         | if $v == "" then error("profile \($name): environment variable \(.k) is not set") else $v end));
    def hostof: capture("^https?://(?<h>[^/]+)/").h;
    def uniq_ordered: reduce .[] as $x ([]; if index([$x]) then . else . + [$x] end);
    ((.profiles | keys) as $ks | if (.default | IN($ks[])) | not then error("default must name a profile") else . end)
    | ($want | if . == "" then ($ENV.VLT_LAB_PROFILE // "") else . end) as $w
    | (if $w == "" then .default else $w end) as $name
    | (.profiles[$name] // error("unknown profile \($name); available: \(.profiles | keys_unsorted | join(", "))"))
    | (.npm | sub($name)) as $npm
    | (if .main then .main | sub($name) else null end) as $main
    | {
        name: $name, npm: $npm, main: $main,
        scope: (if .scope then .scope | sub($name) else null end),
        tokenEnv: (.tokenEnv // null),
        hosts: ([$npm | hostof] + (if $main then [$main | hostof] else [] end)
                + ((.hosts // []) | map(sub($name))) | uniq_ordered),
        scripts: (.scripts // "deny")
      }' "$FILE" 2>&1) && rc=0 || rc=$?
  if [ $rc -ne 0 ]; then printf '%s\n' "$out" | sed 's/^jq: error ([^)]*): //'; return 1; fi
  printf '%s\n' "$out"
}

# Each renderer is a jq program over the resolved profile.
JQ_COMMON='
  def header: "# generated by vlt-lab from profile \(.name); do not edit";
  def routed: .main != null and .scope != null;
  def authkey: sub("^https?:"; "");
  def lines: map(select(. != null)) | join("\n") + "\n";
  def envpairs:
    [ ["npm_config_registry", .npm], ["NPM_CONFIG_REGISTRY", .npm],
      ["YARN_REGISTRY", .npm], ["YARN_NPM_REGISTRY_SERVER", .npm],
      ["VLT_REGISTRY", .npm],
      ["VLT_REGISTRIES", (if .main == null then "npm=\(.npm)" else "npm=\(.npm)\nmain=\(.main)" end)] ]
    + (if routed then [["VLT_SCOPED_REGISTRIES", "\(.scope)=\(.main)"]] else [] end)
    + (if .scripts == "deny" then [["npm_config_ignore_scripts", "true"], ["YARN_ENABLE_SCRIPTS", "false"], ["YARN_IGNORE_SCRIPTS", "true"]] else [] end);
'

render_target() {
  case $1 in
    npmrc) prog='[ header, "registry=\(.npm)",
        (if routed then "\(.scope):registry=\(.main)" else null end),
        (if .tokenEnv then "\(.npm | authkey):_authToken=${\(.tokenEnv)}" else null end),
        (if .tokenEnv and .main then "\(.main | authkey):_authToken=${\(.tokenEnv)}" else null end),
        (if .scripts == "deny" then "ignore-scripts=true" else null end) ] | lines' ;;
    bunfig) prog='
        def reg($u): if .tokenEnv then "{ url = \"\($u)\", token = \"$\(.tokenEnv)\" }" else "\"\($u)\"" end;
        [ header, "[install]", "registry = \(reg(.npm))" ]
        + (if routed then ["", "[install.scopes]", "\"\(.scope[1:])\" = \(reg(.main))"] else [] end) | lines' ;;
    yarnrc) prog='
        def auth($i): if .tokenEnv then ["\($i)npmAlwaysAuth: true", "\($i)npmAuthToken: \"${\(.tokenEnv):-}\""] else [] end;
        ([.npm, .main] | map(select(. != null and startswith("http:")) | capture("^http://(?<h>[^/:]+)").h)
          | reduce .[] as $x ([]; if index([$x]) then . else . + [$x] end)) as $http
        | [ header, "npmRegistryServer: \"\(.npm)\"" ] + auth("")
        + (if routed then ["npmScopes:", "  \(.scope[1:]):", "    npmRegistryServer: \"\(.main)\"",
             "    npmPublishRegistry: \"\(.main)\""] + auth("    ") else [] end)
        + (if .scripts == "deny" then ["enableScripts: false"] else [] end)
        + (if ($http | length) > 0 then ["unsafeHttpWhitelist:"] + ($http | map("  - \"\(.)\"")) else [] end)
        | lines' ;;
    vlt-json) prog='
        { config: ({ registries: (if .main == null then {npm: .npm} else {npm: .npm, main: .main} end) }
          + (if routed then {"scoped-registries": {(.scope): .main}} else {} end)
          + { command: { build: { target: ":scripts:not(:built):not(:malware)" } } }) }
        | tojson' ;;
    env-sh) prog='[header] + (envpairs | map("export \(.[0])='"'"'\(.[1])'"'"'")) | lines' ;;
    env-nu) prog='[header] + (envpairs | map("$env.\(.[0]) = \"\(.[1] | gsub("\n"; "\\n"))\"")) | lines' ;;
    hosts) prog='.hosts | lines' ;;
    *) die "unknown target $1; expected one of: $(echo $TARGETS | sed 's/ /, /g')" ;;
  esac
  if [ "$1" = vlt-json ]; then
    # jq pretty-prints with 2-space indent, matching JSON.stringify(x, null, 2)
    jq "$JQ_COMMON $prog | fromjson"
  else
    jq -j "$JQ_COMMON $prog"
  fi
}

usage() {
  cat <<EOF
usage: registry-profile.sh <command>
  list                      profile names and descriptions (tab separated)
  render <target> [profile] one of: $TARGETS
  validate                  check the profiles document
EOF
}

cmd=${1:-}
[ $# -gt 0 ] && shift
case $cmd in
  list) jq -r '.profiles | to_entries[] | "\(.key)\t\(.value.description // "")"' "$FILE" ;;
  validate) resolve "" >/dev/null && echo ok ;;
  render)
    [ $# -ge 1 ] || { usage >&2; exit 2; }
    target=$1; profile=${2:-}
    case " $TARGETS " in *" $target "*) ;; *) die "unknown target $target; expected one of: $(echo $TARGETS | sed 's/ /, /g')" ;; esac
    resolved=$(resolve "$profile") || die "$resolved"
    printf '%s' "$resolved" | render_target "$target" ;;
  -h|--help) usage ;;
  *) usage >&2; exit 2 ;;
esac
