import type { Profile, Target } from "./schema.ts";

/** A profile with every `{env:NAME}` placeholder substituted. */
export type Resolved = Readonly<{
  name: string;
  npm: string;
  main?: string;
  scope?: string;
  tokenEnv?: string;
  hosts: readonly string[];
  scripts: "deny" | "allow";
}>;

export const BUILD_TARGET = ":scripts:not(:built):not(:malware)";

type Env = Readonly<Record<string, string | undefined>>;

const placeholder = /\{env:([A-Za-z_][A-Za-z0-9_]*)\}/g;

const substitute = (name: string, env: Env) => (s: string): string =>
  s.replace(placeholder, (_, key: string) => {
    const value = env[key];
    if (value === undefined || value === "") {
      throw new Error(`profile ${name}: environment variable ${key} is not set`);
    }
    return value;
  });

/** Hostname (with port when present) of a registry URL. */
export const hostOf = (url: string): string => new URL(url).host;

/** `//host/path/` form used for per-registry auth keys in .npmrc. */
const authKey = (url: string): string => url.replace(/^https?:/, "");

const unique = (xs: readonly string[]): string[] => [...new Set(xs)];

export const resolve = (name: string, p: Profile, env: Env): Resolved => {
  const sub = substitute(name, env);
  const npm = sub(p.npm);
  const main = p.main === undefined ? undefined : sub(p.main);
  const extra = (p.hosts ?? []).map(sub);
  return {
    name,
    npm,
    main,
    scope: p.scope === undefined ? undefined : sub(p.scope),
    tokenEnv: p.tokenEnv,
    hosts: unique([hostOf(npm), ...(main ? [hostOf(main)] : []), ...extra]),
    scripts: p.scripts,
  };
};

const header = (r: Resolved): string => `# generated by vlt-lab from profile ${r.name}; do not edit`;

const lines = (xs: ReadonlyArray<string | false | undefined>): string =>
  `${xs.filter((x): x is string => typeof x === "string").join("\n")}\n`;

const routed = (r: Resolved): r is Resolved & { main: string; scope: string } =>
  r.main !== undefined && r.scope !== undefined;

const npmrc = (r: Resolved): string =>
  lines([
    header(r),
    `registry=${r.npm}`,
    routed(r) && `${r.scope}:registry=${r.main}`,
    r.tokenEnv !== undefined && `${authKey(r.npm)}:_authToken=\${${r.tokenEnv}}`,
    r.tokenEnv !== undefined && r.main !== undefined && `${authKey(r.main)}:_authToken=\${${r.tokenEnv}}`,
    r.scripts === "deny" && "ignore-scripts=true",
  ]);

const tomlRegistry = (url: string, tokenEnv?: string): string =>
  tokenEnv === undefined ? `"${url}"` : `{ url = "${url}", token = "$${tokenEnv}" }`;

const bunfig = (r: Resolved): string =>
  lines([
    header(r),
    "[install]",
    `registry = ${tomlRegistry(r.npm, r.tokenEnv)}`,
    routed(r) && "",
    routed(r) && "[install.scopes]",
    routed(r) && `"${r.scope.slice(1)}" = ${tomlRegistry(r.main, r.tokenEnv)}`,
  ]);

const yarnAuth = (indent: string, tokenEnv?: string): string[] =>
  tokenEnv === undefined
    ? []
    : [`${indent}npmAlwaysAuth: true`, `${indent}npmAuthToken: "\${${tokenEnv}:-}"`];

const yarnrc = (r: Resolved): string => {
  const httpHosts = unique(
    [r.npm, r.main].filter((u): u is string => u?.startsWith("http:") ?? false).map((u) => new URL(u).hostname),
  );
  return lines([
    header(r),
    `npmRegistryServer: "${r.npm}"`,
    ...yarnAuth("", r.tokenEnv),
    ...(routed(r)
      ? [
          "npmScopes:",
          `  ${r.scope.slice(1)}:`,
          `    npmRegistryServer: "${r.main}"`,
          `    npmPublishRegistry: "${r.main}"`,
          ...yarnAuth("    ", r.tokenEnv),
        ]
      : []),
    r.scripts === "deny" && "enableScripts: false",
    ...(httpHosts.length > 0 ? ["unsafeHttpWhitelist:", ...httpHosts.map((h) => `  - "${h}"`)] : []),
  ]);
};

const vltJson = (r: Resolved): string => {
  const config: Record<string, unknown> = {
    registries: r.main === undefined ? { npm: r.npm } : { npm: r.npm, main: r.main },
  };
  if (routed(r)) config["scoped-registries"] = { [r.scope]: r.main };
  config.command = { build: { target: BUILD_TARGET } };
  return `${JSON.stringify({ config }, null, 2)}\n`;
};

/** Environment pairs in a fixed order, shared by the sh and nu renderers. */
export const envPairs = (r: Resolved): Array<[string, string]> => [
  ["npm_config_registry", r.npm],
  ["NPM_CONFIG_REGISTRY", r.npm],
  ["YARN_REGISTRY", r.npm],
  ["YARN_NPM_REGISTRY_SERVER", r.npm],
  // vlt sends VLT_TOKEN to scoped registries only when VLT_REGISTRY is also set
  ["VLT_REGISTRY", r.npm],
  ["VLT_REGISTRIES", r.main === undefined ? `npm=${r.npm}` : `npm=${r.npm}\nmain=${r.main}`],
  ...(routed(r) ? ([["VLT_SCOPED_REGISTRIES", `${r.scope}=${r.main}`]] as Array<[string, string]>) : []),
  ...(r.scripts === "deny"
    ? ([
        ["npm_config_ignore_scripts", "true"],
        ["YARN_ENABLE_SCRIPTS", "false"],
      ] as Array<[string, string]>)
    : []),
];

const envSh = (r: Resolved): string =>
  lines([header(r), ...envPairs(r).map(([k, v]) => `export ${k}='${v}'`)]);

const envNu = (r: Resolved): string =>
  lines([header(r), ...envPairs(r).map(([k, v]) => `$env.${k} = "${v.replaceAll("\n", "\\n")}"`)]);

const hosts = (r: Resolved): string => lines([...r.hosts]);

const renderers: Readonly<Record<Target, (r: Resolved) => string>> = {
  npmrc,
  bunfig,
  yarnrc,
  "vlt-json": vltJson,
  "env-sh": envSh,
  "env-nu": envNu,
  hosts,
};

export const render = (r: Resolved, target: Target): string => renderers[target](r);
