#!/bin/sh
# dispatch.sh <tool> [args...]: PATH shim dispatcher (POSIX sh).
#
# Shims created by install.{sh,nu,ts} exec this with their own name as the first
# argument. VLT_LAB_MODE selects the behaviour:
#   off   exec the real binary unchanged
#   env   load the registry profile environment, then exec the real binary (default)
#   vlt   route dependency installs to `vlt install` + `vlt query ':malware'`,
#         npx/pnpx/bunx/vlx to vlx, everything else like env
#   nono  like env, but run the real binary inside `nono run`
# VLT_LAB_PROFILE picks the profile. VLT_LAB_DRY_RUN=1 prints the commands instead
# of running them. VLT_LAB_DEBUG=1 logs routing decisions to stderr.
set -eu

HERE=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
VL_ROOT=${VL_ROOT:-$(CDPATH='' cd -- "$HERE/../.." && pwd)}
export VL_ROOT
# shellcheck source=../../lib/sh/common.sh
. "$VL_ROOT/lib/sh/common.sh"

[ $# -ge 1 ] || { printf 'usage: dispatch.sh <tool> [args...]\n' >&2; exit 2; }
tool=$1; shift

debug() { [ -z "${VLT_LAB_DEBUG:-}" ] || printf 'vlt-lab: %s\n' "$*" >&2; }

# Every dispatcher on the way records its shim dir in VLT_LAB_SHIM_SEEN, and real
# binaries are looked up on a PATH without any of those dirs. Without this, two
# different shim dirs on PATH would hand a pass-through call back and forth forever.
_self=$(CDPATH='' cd -- "$VL_SHIM_DIR" 2>/dev/null && pwd -P || printf '%s' "$VL_SHIM_DIR")
case ":${VLT_LAB_SHIM_SEEN:-}:" in
  *":$_self:"*) ;;
  *) VLT_LAB_SHIM_SEEN=${VLT_LAB_SHIM_SEEN:+$VLT_LAB_SHIM_SEEN:}$_self ;;
esac
export VLT_LAB_SHIM_SEEN

# unseen_path: $PATH without the shim dirs in VLT_LAB_SHIM_SEEN
unseen_path() {
  _out=""; _old_ifs=$IFS; IFS=:
  for _d in $PATH; do
    _dp=$(CDPATH='' cd -- "$_d" 2>/dev/null && pwd -P) || continue
    case ":$VLT_LAB_SHIM_SEEN:" in *":$_dp:"*) continue ;; esac
    _out=${_out:+$_out:}$_d
  done
  IFS=$_old_ifs
  printf '%s' "$_out"
}

# real <name>: real binary outside the shim dirs, or exit 127
real() {
  (PATH=$(unseen_path); vl_real_bin "$1") ||
    { printf 'vlt-lab: %s not found outside %s\n' "$1" "$VL_SHIM_DIR" >&2; exit 127; }
}

# exec_cmd <argv...>: exec, or print the argv under VLT_LAB_DRY_RUN
exec_cmd() {
  if [ -n "${VLT_LAB_DRY_RUN:-}" ]; then printf '%s\n' "$*"; exit 0; fi
  exec "$@"
}

REAL=$(real "$tool")
MODE=${VLT_LAB_MODE:-env}
DEPTH=${VLT_LAB_SHIM_DEPTH:-0}
case $DEPTH in '' | *[!0-9]*) DEPTH=0 ;; esac

if [ "$MODE" = off ]; then debug "$tool: mode off -> $REAL"; exec_cmd "$REAL" "$@"; fi
if [ "$DEPTH" -ge 1 ]; then
  debug "$tool: depth guard (VLT_LAB_SHIM_DEPTH=$DEPTH) -> $REAL"
  exec_cmd "$REAL" "$@"
fi
VLT_LAB_SHIM_DEPTH=$((DEPTH + 1)); export VLT_LAB_SHIM_DEPTH

# load_env: profile environment, plus a rendered npmrc for token profiles
load_env() {
  _envsh=$(vl_profile render env-sh) || exit 1
  eval "$_envsh"
  _npmrc=$(vl_profile render npmrc) || exit 1
  PROFILE_NAME=$(printf '%s\n' "$_npmrc" | sed -n '1s/^# generated by vlt-lab from profile \([^;]*\); do not edit$/\1/p')
  _tokvar=$(printf '%s\n' "$_npmrc" | sed -n 's/^.*:_authToken=\${\([A-Za-z_][A-Za-z0-9_]*\)}$/\1/p' | sed -n 1p)
  [ -n "$_tokvar" ] || return 0
  eval "_tokval=\${$_tokvar:-}"
  if [ -z "$_tokval" ]; then
    vl_log "warning: profile $PROFILE_NAME expects \$$_tokvar, which is not set; requests go unauthenticated"
    return 0
  fi
  case $tool in
    npm | npx | pnpm | pnpx | yarn)
      # npm, pnpm and yarn classic read npm_config_userconfig; $HOME/.npmrc stays untouched
      _dir=${TMPDIR:-/tmp}/vlt-lab-$(id -u)
      mkdir -p "$_dir" && chmod 700 "$_dir"
      USERCONFIG=$_dir/$PROFILE_NAME.npmrc
      printf '%s\n' "$_npmrc" > "$USERCONFIG.$$" && mv -f "$USERCONFIG.$$" "$USERCONFIG"
      npm_config_userconfig=$USERCONFIG NPM_CONFIG_USERCONFIG=$USERCONFIG
      export npm_config_userconfig NPM_CONFIG_USERCONFIG
      # yarn classic only sends the token with always-auth
      if [ "$tool" = yarn ]; then npm_config_always_auth=true; export npm_config_always_auth; fi
      ;;
    bun | bunx)
      # bun ignores npm_config_userconfig but sends NPM_CONFIG_TOKEN to the default registry
      NPM_CONFIG_TOKEN=$_tokval; export NPM_CONFIG_TOKEN ;;
    vlx)
      [ "$_tokvar" = VLT_TOKEN ] || { VLT_TOKEN=$_tokval; export VLT_TOKEN; } ;;
  esac
}
USERCONFIG=""
PROFILE_NAME=""
_tokvar=""
_tokval=""

# install_verb: true when the call is a dependency install with no package args
install_verb() {
  case $tool in
    npm) case ${1:-} in install | i | ci) shift ;; *) return 1 ;; esac ;;
    pnpm | bun) case ${1:-} in install | i) shift ;; *) return 1 ;; esac ;;
    yarn) case ${1:-} in install) shift ;; -* | '') ;; *) return 1 ;; esac ;;
    *) return 1 ;;
  esac
  for _a in "$@"; do case $_a in -*) ;; *) return 1 ;; esac; done
  return 0
}

run_vlt_install() {
  load_env
  # vlt reads VLT_TOKEN; map a differently named profile token onto it
  if [ -n "$_tokval" ] && [ "$_tokvar" != VLT_TOKEN ]; then VLT_TOKEN=$_tokval; export VLT_TOKEN; fi
  _vlt=$(real vlt)
  _sub=install
  if [ "$tool" = npm ] && [ "${1:-}" = ci ] && [ -f vlt-lock.json ]; then _sub=ci; fi
  [ $# -le 1 ] || vl_log "vlt mode: ignoring $tool flags: $(shift; printf '%s ' "$@")"
  if [ -n "${VLT_LAB_DRY_RUN:-}" ]; then
    printf '%s\n' "$_vlt $_sub" "$_vlt query :malware --expect-results=0"
    exit 0
  fi
  vl_log "vlt mode: $tool $* -> vlt $_sub (profile $PROFILE_NAME)"
  "$_vlt" "$_sub" || { _rc=$?; vl_log "summary: vlt $_sub failed (exit $_rc)"; exit "$_rc"; }
  if _q=$("$_vlt" query ':malware' --expect-results=0 2>&1); then
    vl_log "summary: vlt $_sub ok; vlt-lock.json written; :malware matched 0 packages"
  else
    _rc=$?
    printf '%s\n' "$_q" >&2
    vl_log "summary: vlt $_sub ok; :malware check failed (exit $_rc); see output above"
    exit "$_rc"
  fi
  exit 0
}

# package_root <file>: nearest ancestor holding package.json (4 levels), else its dir
package_root() {
  _d=$(dirname -- "$1"); _i=0
  while [ "$_i" -lt 4 ] && [ "$_d" != / ]; do
    [ -f "$_d/package.json" ] && { printf '%s\n' "$_d"; return 0; }
    _d=$(dirname -- "$_d"); _i=$((_i + 1))
  done
  dirname -- "$1"
}

# project_root: nearest ancestor of $PWD with package.json, else $PWD
project_root() {
  _d=$PWD
  while [ "$_d" != / ]; do
    [ -f "$_d/package.json" ] && { printf '%s\n' "$_d"; return 0; }
    _d=$(dirname -- "$_d")
  done
  printf '%s\n' "$PWD"
}

# tool_caches: directories the tool writes outside the project
tool_caches() {
  _h=${HOME:-/nonexistent}
  case $tool in
    npm | npx) printf '%s\n' "${npm_config_cache:-$_h/.npm}" ;;
    pnpm | pnpx) printf '%s\n' "${XDG_DATA_HOME:-$_h/.local/share}/pnpm" "${XDG_CACHE_HOME:-$_h/.cache}/pnpm" ;;
    yarn) printf '%s\n' "${XDG_CACHE_HOME:-$_h/.cache}/yarn" ;;
    bun | bunx) printf '%s\n' "${BUN_INSTALL_CACHE_DIR:-$_h/.bun/install/cache}" ;;
    vlx) printf '%s\n' "${XDG_CACHE_HOME:-$_h/.cache}/vlt" "${XDG_DATA_HOME:-$_h/.local/share}/vlt" ;;
  esac
}

# user_configs: config files the tool reads outside the project. Only existing files
# are granted; an ungranted file is silently skipped by the tool. ~/.npmrc,
# ~/.bunfig.toml and ~/.config/bun/bunfig.toml are left out on purpose: nono's
# required deny_credentials group blocks them, so inside the sandbox the profile
# environment (and the rendered npmrc for token profiles) is the whole config.
user_configs() {
  _h=${HOME:-/nonexistent}
  _cfg=${XDG_CONFIG_HOME:-$_h/.config}
  _uc=${npm_config_userconfig:-${NPM_CONFIG_USERCONFIG:-}}
  case $tool in
    npm | npx) printf '%s\n' "$_uc" ;;
    pnpm | pnpx) printf '%s\n' "$_uc" "$_cfg/pnpm/rc" ;;
    # yarn classic aborts when $PREFIX/etc/npmrc exists but is unreadable (npm and pnpm only warn)
    yarn) printf '%s\n' "$_uc" "$_h/.yarnrc" "$(dirname -- "$(dirname -- "$REAL")")/etc/npmrc" ;;
    vlx) printf '%s\n' "$_cfg/vlt/vlt.json" ;;
  esac
}

run_nono() {
  load_env
  # client-specific proxy settings would bypass the proxy nono injects
  unset npm_config_proxy npm_config_https_proxy npm_config_http_proxy npm_config_noproxy npm_config_no_proxy \
    NPM_CONFIG_PROXY NPM_CONFIG_HTTPS_PROXY NPM_CONFIG_HTTP_PROXY NPM_CONFIG_NOPROXY NPM_CONFIG_NO_PROXY \
    YARN_PROXY YARN_HTTPS_PROXY YARN_HTTP_PROXY 2>/dev/null || true
  _nono=$(real nono)
  _hosts=$(vl_profile render hosts) || exit 1
  _rp=$(readlink -f -- "$REAL" 2>/dev/null || printf '%s' "$REAL")
  _n=$#
  set -- "$@" run -s --allow "$(project_root)"
  for _h in $_hosts; do set -- "$@" --allow-domain "$_h"; done
  set -- "$@" --allow-command "$tool" --read "$(dirname -- "$REAL")"
  _root=$(package_root "$_rp")
  [ "$_root" = "$(dirname -- "$REAL")" ] || set -- "$@" --read "$_root"
  _caches=$(tool_caches)
  _old_ifs=$IFS
  IFS='
'
  for _c in $_caches; do mkdir -p "$_c"; set -- "$@" --allow "$_c"; done
  IFS=$_old_ifs
  for _f in "${SSL_CERT_FILE:-}" "${NODE_EXTRA_CA_CERTS:-}"; do
    [ -n "$_f" ] && [ -f "$_f" ] || continue
    [ "$_f" = "${_seen_ca:-}" ] && continue
    set -- "$@" --read-file "$_f"; _seen_ca=$_f
  done
  _cfgs=$(user_configs)
  IFS='
'
  for _f in $_cfgs; do [ -f "$_f" ] && set -- "$@" --read-file "$_f"; done
  IFS=$_old_ifs
  set -- "$@" -- "$REAL"
  # move the original tool arguments behind the nono prefix
  while [ "$_n" -gt 0 ]; do _a=$1; shift; set -- "$@" "$_a"; _n=$((_n - 1)); done
  debug "$tool: mode nono -> $_nono $*"
  exec_cmd "$_nono" "$@"
}

case $MODE in
  env)
    load_env; debug "$tool: mode env (profile $PROFILE_NAME) -> $REAL"; exec_cmd "$REAL" "$@" ;;
  vlt)
    if install_verb "$@"; then run_vlt_install "$@"; fi
    case $tool in
      npx | pnpx | bunx | vlx)
        _orig=$tool; tool=vlx; load_env; _vlx=$(real vlx)
        debug "$_orig: mode vlt -> $_vlx"; exec_cmd "$_vlx" "$@" ;;
    esac
    load_env; debug "$tool: mode vlt, not an install -> $REAL"; exec_cmd "$REAL" "$@" ;;
  nono) run_nono "$@" ;;
  *) printf 'vlt-lab: unknown VLT_LAB_MODE %s (expected off, env, vlt, nono)\n' "$MODE" >&2; exit 2 ;;
esac
