#!/usr/bin/env bun
// install.ts: create PATH shims that exec a vlt-lab dispatcher.
// Same flags and output as install.sh; shim files are byte-identical.
import { chmodSync, existsSync, mkdirSync, readFileSync, realpathSync, renameSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { parseArgs } from "node:util";
import { die, realBin, shimDir } from "../../lib/ts/common.ts";

const TOOLS = ["npm", "npx", "pnpm", "pnpx", "yarn", "bun", "bunx", "vlx"];
const HEADER = "# generated by vlt-lab install";
const USAGE = "usage: install [--impl sh|nu|ts] [--dir DIR] [--force]";

/** single-quote for sh */
const q = (s: string): string => `'${s.replaceAll("'", "'\\''")}'`;

const { values } = parseArgs({
  args: process.argv.slice(2),
  options: {
    impl: { type: "string", default: "sh" },
    dir: { type: "string" },
    force: { type: "boolean", default: false },
    help: { type: "boolean", short: "h" },
  },
});
if (values.help) {
  console.log(USAGE);
  process.exit(0);
}

const requested = values.dir ?? shimDir();
mkdirSync(requested, { recursive: true });
const dir = realpathSync(requested);
// resolve interpreters outside the shim dir so a shim never runs another shim
const lookup = (name: string): string => {
  const hit = realBin(name, { ...process.env, VLT_LAB_SHIM_DIR: dir }) ?? die(`${name} not found on PATH`);
  return join(realpathSync(dirname(hit)), basename(hit));
};
const interp =
  values.impl === "sh" ? "/bin/sh"
  : values.impl === "nu" ? lookup("nu")
  : values.impl === "ts" ? lookup("bun")
  : die(`unknown --impl ${values.impl} (expected sh, nu or ts)`);
const dispatcher = join(import.meta.dir, `dispatch.${values.impl}`);

for (const t of TOOLS) {
  const f = join(dir, t);
  if (existsSync(f) && !values.force) {
    const second = readFileSync(f, "utf8").split("\n")[1] ?? "";
    if (!second.startsWith(HEADER)) die(`${f} exists and is not a vlt-lab shim (use --force to replace it)`);
  }
  const body = [
    "#!/bin/sh",
    `${HEADER} (impl ${values.impl}); do not edit`,
    `VLT_LAB_SHIM_DIR=${q(dir)}; export VLT_LAB_SHIM_DIR`,
    `exec ${q(interp)} ${q(dispatcher)} ${t} "$@"`,
  ].join("\n");
  const tmp = `${f}.vlt-lab.tmp.${process.pid}`;
  writeFileSync(tmp, `${body}\n`);
  chmodSync(tmp, 0o755);
  renameSync(tmp, f);
}

console.log(`installed ${TOOLS.length} shims (impl ${values.impl}) in ${dir}`);
console.log("add to PATH (rc files are not edited):");
console.log(`  sh: export PATH="${dir}:$PATH"`);
console.log(`  nu: $env.PATH = ($env.PATH | prepend '${dir}')`);
