#!/bin/sh
# install.sh: create PATH shims that exec a vlt-lab dispatcher.
#
#   sh install.sh [--impl sh|nu|ts] [--dir DIR] [--force]
#
# Default dir: ${VLT_LAB_SHIM_DIR:-$XDG_DATA_HOME/vlt-lab/shims}. Existing files are
# replaced only when they are vlt-lab shims (or with --force). Shell rc files are
# never edited; the PATH line to add is printed instead.
set -eu

HERE=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
VL_ROOT=$(CDPATH='' cd -- "$HERE/../.." && pwd)
export VL_ROOT
# shellcheck source=../../lib/sh/common.sh
. "$VL_ROOT/lib/sh/common.sh"

TOOLS="npm npx pnpm pnpx yarn bun bunx vlx"
impl=sh; dir=$VL_SHIM_DIR; force=0
while [ $# -gt 0 ]; do
  case $1 in
    --impl) [ $# -ge 2 ] || vl_die "--impl needs a value"; impl=$2; shift 2 ;;
    --impl=*) impl=${1#*=}; shift ;;
    --dir) [ $# -ge 2 ] || vl_die "--dir needs a value"; dir=$2; shift 2 ;;
    --dir=*) dir=${1#*=}; shift ;;
    --force) force=1; shift ;;
    -h | --help) printf 'usage: install [--impl sh|nu|ts] [--dir DIR] [--force]\n'; exit 0 ;;
    *) printf 'usage: install [--impl sh|nu|ts] [--dir DIR] [--force]\n' >&2; exit 2 ;;
  esac
done

mkdir -p "$dir"
dir=$(CDPATH='' cd -- "$dir" && pwd -P)
# resolve interpreters outside the shim dir so a shim never runs another shim
VL_SHIM_DIR=$dir
case $impl in
  sh) interp=/bin/sh ;;
  nu) interp=$(vl_real_bin nu) || vl_die "nu not found on PATH" ;;
  ts) interp=$(vl_real_bin bun) || vl_die "bun not found on PATH" ;;
  *) vl_die "unknown --impl $impl (expected sh, nu or ts)" ;;
esac
dispatcher=$HERE/dispatch.$impl

# q <s>: single-quote for sh
q() { printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"; }

HEADER='# generated by vlt-lab install'
for t in $TOOLS; do
  f=$dir/$t
  if [ -e "$f" ] && [ "$force" -ne 1 ] && ! sed -n 2p "$f" 2>/dev/null | grep -q "^$HEADER"; then
    vl_die "$f exists and is not a vlt-lab shim (use --force to replace it)"
  fi
  {
    printf '#!/bin/sh\n'
    printf '%s (impl %s); do not edit\n' "$HEADER" "$impl"
    printf 'VLT_LAB_SHIM_DIR=%s; export VLT_LAB_SHIM_DIR\n' "$(q "$dir")"
    printf 'exec %s %s %s "$@"\n' "$(q "$interp")" "$(q "$dispatcher")" "$t"
  } > "$f.vlt-lab.tmp.$$"
  chmod 755 "$f.vlt-lab.tmp.$$"
  mv -f "$f.vlt-lab.tmp.$$" "$f"
done

printf 'installed %s shims (impl %s) in %s\n' "$(echo $TOOLS | wc -w | tr -d ' ')" "$impl" "$dir"
printf 'add to PATH (rc files are not edited):\n'
printf '  sh: export PATH="%s:$PATH"\n' "$dir"
printf "  nu: \$env.PATH = (\$env.PATH | prepend '%s')\n" "$dir"
