#!/usr/bin/env nu
# install.nu: create PATH shims that exec a vlt-lab dispatcher.
# Same flags and output as install.sh; shim files are byte-identical.

use ../../lib/nu/common.nu *

const TOOLS = [npm npx pnpm pnpx yarn bun bunx vlx]
const HEADER = "# generated by vlt-lab install"
const HERE = path self .

# single-quote for sh
def q [s: string]: nothing -> string { $"'($s | str replace --all "'" "'\\''")'" }

# Create PATH shims for npm npx pnpm pnpx yarn bun bunx vlx.
def main [
  --impl: string = "sh"  # dispatcher implementation: sh, nu or ts
  --dir: string          # shim directory (default: $VLT_LAB_SHIM_DIR, then $XDG_DATA_HOME/vlt-lab/shims)
  --force                # replace files that are not vlt-lab shims
] {
  let target = $dir | default (vl-shim-dir)
  mkdir $target
  let target = $target | path expand
  # resolve interpreters outside the shim dir so a shim never runs another shim
  let interp = with-env {VLT_LAB_SHIM_DIR: $target} {
    match $impl {
      sh => "/bin/sh"
      nu => (try { vl-real-bin nu } catch { error make --unspanned { msg: "nu not found on PATH" } })
      ts => (try { vl-real-bin bun } catch { error make --unspanned { msg: "bun not found on PATH" } })
      _ => { error make --unspanned { msg: $"unknown --impl ($impl) \(expected sh, nu or ts\)" } }
    }
  }
  let interp = if $interp == "/bin/sh" { $interp } else { $interp | path dirname | path expand | path join ($interp | path basename) }
  let dispatcher = $HERE | path join $"dispatch.($impl)"
  for t in $TOOLS {
    let f = $target | path join $t
    if ($f | path exists) and not $force {
      let second = open --raw $f | decode utf-8 | lines | get 1? | default ""
      if not ($second | str starts-with $HEADER) {
        error make --unspanned { msg: $"($f) exists and is not a vlt-lab shim \(use --force to replace it\)" }
      }
    }
    let body = [
      "#!/bin/sh"
      $"($HEADER) \(impl ($impl)\); do not edit"
      $"VLT_LAB_SHIM_DIR=(q $target); export VLT_LAB_SHIM_DIR"
      $"exec (q $interp) (q $dispatcher) ($t) \"$@\""
    ] | str join "\n"
    let tmp = $"($f).vlt-lab.tmp.($nu.pid)"
    $"($body)\n" | save --raw --force $tmp
    ^chmod 755 $tmp
    ^mv -f $tmp $f
  }
  print $"installed ($TOOLS | length) shims \(impl ($impl)\) in ($target)"
  print "add to PATH (rc files are not edited):"
  print $"  sh: export PATH=\"($target):$PATH\""
  print $"  nu: $env.PATH = \($env.PATH | prepend '($target)'\)"
}
