#!/bin/sh
# fork-install.sh: install a possibly hostile repository with vlt, every phase that touches its
# packages running under its own nono sandbox. Composes examples/04 (phases) and examples/07
# (sandboxes); see README.md.
#
#   sh fork-install.sh <git-url|path> [--ref REF] [--profile REGISTRY_PROFILE] [--gate FILE]
#                      [--build SELECTOR] [--no-build] [--permissive] [--native] [--out DIR] [--keep]
#
# stdout: the path of the merged JSON report. stderr: progress and a summary table.
# exit: first failing phase's code (0 ok, 1 internal, 2 refused/usage, 3 gate blocked,
#       4 clone or package fetch failed, 5 build failed).
set -eu

HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
VL_ROOT=$(CDPATH= cd -- "$HERE/../.." && pwd -P)
. "$VL_ROOT/lib/sh/common.sh"

IMPL=sh
D04=$VL_ROOT/examples/04-vlt-as-installer
D07=$VL_ROOT/examples/07-nono-sandboxing
# interpreter and file extension of the 04 phase runner and the 07 sandbox wrapper
RUNNER_CMD=sh; RUNNER_EXT=sh
DEFAULT_BUILD=':scripts:not(:built):not(:malware)'
GIT_HARDENING="core.hooksPath=/dev/null core.fsmonitor=false protocol.file.allow=never protocol.ext.allow=never transfer.fsckObjects=true submodule.recurse=false"
PM_CONFIGS=".npmrc .yarnrc .yarnrc.yml bunfig.toml .pnpmfile.cjs .pnpmfile.mjs"

usage() {
  sed -n '5,7p' "$0" | sed 's/^# \{0,1\}//' >&2
  exit 2
}

now_ms() { date +%s%3N; }

SOURCE=""; REF=""; PROFILE=""; GATE=""; BUILD_SEL=$DEFAULT_BUILD; NO_BUILD=0; PERMISSIVE=0; NATIVE=0; OUT=""; KEEP=0
while [ $# -gt 0 ]; do
  case $1 in
    --ref) [ $# -ge 2 ] || usage; REF=$2; shift 2 ;;
    --profile) [ $# -ge 2 ] || usage; PROFILE=$2; shift 2 ;;
    --gate) [ $# -ge 2 ] || usage; GATE=$2; shift 2 ;;
    --build) [ $# -ge 2 ] || usage; BUILD_SEL=$2; shift 2 ;;
    --no-build) NO_BUILD=1; shift ;;
    --permissive) PERMISSIVE=1; shift ;;
    --native) NATIVE=1; shift ;;
    --out) [ $# -ge 2 ] || usage; OUT=$2; shift 2 ;;
    --keep) KEEP=1; shift ;;
    -h|--help) usage ;;
    -*) vl_log "unknown option: $1"; usage ;;
    *) [ -z "$SOURCE" ] || usage; SOURCE=$1; shift ;;
  esac
done
[ -n "$SOURCE" ] || usage
case $REF in -*) vl_log "--ref must not start with '-'"; exit 2 ;; esac
vl_need git jq nono vlt sha256sum node
if [ -n "$GATE" ]; then
  [ -f "$GATE" ] || { vl_log "gate file not found: $GATE"; exit 2; }
  GATE=$(CDPATH= cd -- "$(dirname -- "$GATE")" && pwd -P)/$(basename -- "$GATE")
fi
[ -n "$OUT" ] || OUT=$VL_ROOT/.tmp/fork-reports
PROFILE_NAME=$(vl_profile render env-sh ${PROFILE:+"$PROFILE"} | sed -n '1s/^# generated by vlt-lab from profile \(.*\); do not edit$/\1/p') \
  || { vl_log "cannot render registry profile ${PROFILE:-<default>}"; exit 2; }
[ -n "$PROFILE_NAME" ] || { vl_log "cannot render registry profile ${PROFILE:-<default>}"; exit 2; }

# ---------------------------------------------------------------- input kind and slug
if [ -d "$SOURCE" ]; then
  KIND=path
  SRC_ABS=$(CDPATH= cd -- "$SOURCE" && pwd -P)
  base=$(basename -- "$SRC_ABS")
else
  case $SOURCE in
    *://*|git@*:*|*.git) KIND=git ;;
    *) vl_log "not a directory or git URL: $SOURCE"; exit 2 ;;
  esac
  SRC_ABS=""
  base=$(printf '%s' "$SOURCE" | sed -e 's#/*$##' -e 's#\.git$##' | tr ':' '/' | awk -F/ '{ n = 0; for (i = 1; i <= NF; i++) if ($i != "") a[++n] = $i; print (n >= 2 ? a[n-1] "-" a[n] : a[n]) }')
fi
SLUG=$(printf '%s' "$base" | tr 'A-Z' 'a-z' | sed -e 's/[^a-z0-9._-]\{1,\}/-/g' -e 's/^-*//' -e 's/-*$//')
[ -n "$SLUG" ] || SLUG=repo

SCR=$(vl_scratch fork-install)
if [ "$KIND" = path ]; then
  case "$SCR/" in "$SRC_ABS"/*) vl_log "refusing: $SRC_ABS contains the scratch dir $SCR"; rm -rf "$SCR"; exit 2 ;; esac
fi
cleanup() { if [ $KEEP -eq 0 ]; then rm -rf "$SCR"; fi; }
trap cleanup EXIT
trap 'exit 130' INT TERM
REPO=$SCR/repo; STATE=$SCR/state; SBUILD=$SCR/state-build; NEUT=$SCR/neutralized; PH=$SCR/phases; LOGS=$SCR/logs
mkdir -p "$STATE" "$SBUILD" "$NEUT" "$PH" "$LOGS" "$SCR/nono"
vl_log "fork-install ($IMPL): $SOURCE -> $SCR"

# phase records: rec_skip <name> <reason>; rec_local <name> <exit> <started-ms> <duration-ms>
rec_skip() { jq -nc --arg r "$2" '{ran: false, exit: null, startedAtMs: null, durationMs: null, skipReason: $r, sandbox: null}' >"$PH/$1.json"; }
rec_local() { jq -nc --argjson e "$2" --argjson s "$3" --argjson d "$4" '{ran: true, exit: $e, startedAtMs: $s, durationMs: $d, skipReason: null, sandbox: null}' >"$PH/$1.json"; }

# ---------------------------------------------------------------- acquire
AQ_T0=$(now_ms); t0=$AQ_T0; AQ_EXIT=0; AQ_ERR=""; COMMIT=""
GITC=""; for c in $GIT_HARDENING; do GITC="$GITC -c $c"; done
if [ "$KIND" = git ]; then
  # shellcheck disable=SC2086
  if ! GIT_TERMINAL_PROMPT=0 GIT_LFS_SKIP_SMUDGE=1 git $GITC clone --quiet --depth 1 --single-branch --no-recurse-submodules \
      ${REF:+--branch "$REF"} -- "$SOURCE" "$REPO" >"$LOGS/acquire.log" 2>&1; then
    AQ_EXIT=4; AQ_ERR="git clone failed: $(grep -v '^[[:space:]]*$' "$LOGS/acquire.log" | tail -n 1)"
  else
    # shellcheck disable=SC2086
    COMMIT=$(git $GITC -C "$REPO" rev-parse HEAD 2>/dev/null || true)
  fi
else
  [ -z "$REF" ] || vl_log "warning: --ref is ignored for a local path"
  mkdir -p "$REPO"
  cp -R "$SRC_ABS/." "$REPO/" 2>"$LOGS/acquire.log" || { AQ_EXIT=2; AQ_ERR="copy failed: $(tail -n 1 "$LOGS/acquire.log")"; }
fi
GITDIR=false; NODEMODS=false; SYMS='[]'; NEUTS='[]'; VJ='null'
if [ $AQ_EXIT -eq 0 ]; then
  # .git: hooks or config planted by a build script must never run later in a kept tree
  if [ -e "$REPO/.git" ]; then rm -rf "$REPO/.git"; GITDIR=true; fi
  if [ -e "$REPO/node_modules" ]; then rm -rf "$REPO/node_modules"; NODEMODS=true; fi
  # symlinks that resolve outside the tree (or nowhere) are removed before anything reads them
  REPO_REAL=$(CDPATH= cd -- "$REPO" && pwd -P)
  SYMS=$(cd "$REPO" && find . -type l | sed 's#^\./##' | LC_ALL=C sort | while IFS= read -r l; do
    r=$(readlink -f -- "$REPO/$l" 2>/dev/null || true)
    case $r in "$REPO_REAL"|"$REPO_REAL"/*) ;; *) rm -f -- "$REPO/$l"; printf '%s\n' "$l" ;; esac
  done | jq -Rsc 'split("\n") | map(select(. != ""))')
  # package-manager config files that can redirect registries or run code: moved aside
  for f in $PM_CONFIGS; do
    if [ -f "$REPO/$f" ] && [ ! -L "$REPO/$f" ]; then
      s=$(sha256sum "$REPO/$f" | cut -d' ' -f1)
      mv "$REPO/$f" "$NEUT/$f"
      NEUTS=$(printf '%s' "$NEUTS" | jq -c --arg f "$f" --arg s "$s" '. + [{file: $f, action: "moved", sha256: $s}]')
    fi
  done
  # vlt.json: keep only graph keys, drop all config; pin the project root
  if [ -f "$REPO/vlt.json" ]; then
    s=$(sha256sum "$REPO/vlt.json" | cut -d' ' -f1)
    cp "$REPO/vlt.json" "$NEUT/vlt.json"
    if res=$(jq -c -f "$HERE/sanitize-vlt-json.jq" "$NEUT/vlt.json" 2>/dev/null); then perr=false
    else perr=true; res='{"sanitized":{},"keptKeys":[],"droppedTopLevel":[],"droppedConfigKeys":[],"dangerousKeys":[],"registryHosts":[]}'; fi
    rm -f "$REPO/vlt.json"
    printf '%s' "$res" | jq '.sanitized' >"$REPO/vlt.json"
    VJ=$(printf '%s' "$res" | jq -c --arg s "$s" --argjson pe "$perr" '{present: true, sha256: $s, parseError: $pe} + (del(.sanitized))')
    NEUTS=$(printf '%s' "$NEUTS" | jq -c --arg s "$s" '. + [{file: "vlt.json", action: "rewritten", sha256: $s}]')
  else
    printf '{}\n' >"$REPO/vlt.json"
    VJ='{"present":false,"sha256":null,"parseError":null,"keptKeys":[],"droppedTopLevel":[],"droppedConfigKeys":[],"dangerousKeys":[],"registryHosts":[]}'
    NEUTS=$(printf '%s' "$NEUTS" | jq -c '. + [{file: "vlt.json", action: "created", sha256: null}]')
  fi
fi
AQ_MS=$(($(now_ms) - t0))
jq -n --argjson e $AQ_EXIT --arg err "$AQ_ERR" --arg kind "$KIND" --arg gc "$GIT_HARDENING" \
  --argjson gd $GITDIR --argjson nm $NODEMODS --argjson sy "$SYMS" --argjson ne "$NEUTS" --argjson vj "$VJ" \
  '{exit: $e, error: (if $err == "" then null else $err end),
    gitConfig: (if $kind == "git" then ($gc | split(" ")) else [] end),
    removed: {gitDir: $gd, nodeModules: $nm, externalSymlinks: $sy}, neutralized: $ne, vltJson: $vj}' >"$SCR/acquire.json"
rec_local acquire $AQ_EXIT $AQ_T0 $AQ_MS
[ $AQ_EXIT -eq 0 ] && vl_log "acquire: ok${COMMIT:+ at $COMMIT}" || vl_log "acquire: $AQ_ERR"

# ---------------------------------------------------------------- sandbox helper
# q <word>: single-quote one word for eval
q() { printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"; }

# Toolchain grants for running the 04 phase runners inside 07's sandboxes. --exec replaces the
# phase command, so 07 no longer derives vlt's package dir from argv[0]; it is granted here.
vlt_dir() {
  _r=$(readlink -f "$(command -v vlt)"); _d=$(dirname "$_r"); _w=$_d; _i=0
  while [ $_i -lt 4 ] && [ "$_w" != / ]; do
    if [ -f "$_w/package.json" ]; then _d=$_w; break; fi
    _w=$(dirname "$_w"); _i=$((_i + 1))
  done
  printf '%s\n' "$_d"
}
GR=""
for g in "$VL_ROOT/lib" "$VL_ROOT/config" "$VL_ROOT/packages" "$VL_ROOT/node_modules" "$D04" "$(vlt_dir)"; do
  GR="$GR --read $(q "$g")"
done
PA="--profile $(q "$PROFILE_NAME")"
R04="$RUNNER_CMD $(q "$D04/vlt-install-any.$RUNNER_EXT")"

# sandboxed <name> <07-phase> <wrapper flags...> [-- <command...>]
sandboxed() {
  _name=$1; _ph=$2; shift 2
  _st=$SCR/nono/$_name; mkdir -p "$_st"
  _t0=$(now_ms)
  XDG_STATE_HOME=$_st $RUNNER_CMD "$D07/sandbox-phase.$RUNNER_EXT" "$_ph" --project "$REPO" "$@" >"$LOGS/$_name.log" 2>&1 && _rc=0 || _rc=$?
  _ms=$(($(now_ms) - _t0))
  _perm=false; [ "$_ph" != build ] || [ $PERMISSIVE -eq 0 ] || _perm=true
  _pf=$(jq -r --arg p "$_ph" --argjson perm $_perm '.phases[$p] | if $perm then .permissiveProfile else .profile end' "$D07/phases.json")
  _net=$(jq -r --arg p "$_ph" '.phases[$p].network' "$D07/phases.json")
  _id=$(XDG_STATE_HOME=$_st nono audit list --json 2>/dev/null \
    | jq -r 'if type == "array" then (sort_by(.started) | last | .session_id // empty) else empty end' 2>/dev/null || true)
  if [ -n "$_id" ] && _au=$(XDG_STATE_HOME=$_st nono audit show "$_id" --json 2>/dev/null | jq -c '{auditSession: .session_id,
        networkAllowed: ([.network_events[]? | select(.decision == "allow")] | length),
        networkDenied: ([.network_events[]? | select(.decision != "allow") | {target, port}]
                        | group_by([.target, .port]) | map(.[0] + {count: length}))}' 2>/dev/null) && [ -n "$_au" ]; then :
  else _au='{"auditSession":null,"networkAllowed":null,"networkDenied":null}'; fi
  jq -nc --argjson e $_rc --argjson s $_t0 --argjson d $_ms --arg ph "$_ph" --arg pf "examples/07-nono-sandboxing/profiles/$_pf" --arg net "$_net" --argjson au "$_au" \
    '{ran: true, exit: $e, startedAtMs: $s, durationMs: $d, skipReason: null, sandbox: ({phase: $ph, profile: $pf, network: $net} + $au)}' >"$PH/$_name.json"
  return $_rc
}

# ---------------------------------------------------------------- detect, fetch, gate, build, report
if [ $AQ_EXIT -ne 0 ]; then
  for p in detect fetch gate build report; do rec_skip $p acquire-failed; done
else
  # detect only reads files (after the acquire clean-up) and asks vlt for the project root
  t0=$(now_ms)
  eval "$R04 phase detect --state $(q "$STATE") $PA $(q "$REPO")" >"$LOGS/detect.log" 2>&1 && rc=0 || rc=$?
  rec_local detect $rc $t0 $(($(now_ms) - t0))
  if [ $rc -ne 0 ]; then
    for p in fetch gate build; do rec_skip $p detect-failed; done
  elif [ $NATIVE -eq 0 ]; then
    eval "sandboxed fetch fetch $PA $GR --allow $(q "$STATE") --exec -- $R04 phase fetch --state $(q "$STATE") $PA $(q "$REPO")" && rc=0 || rc=$?
    if [ $rc -ne 0 ]; then
      rec_skip gate fetch-failed; rec_skip build fetch-failed
    else
      cp "${GATE:-$D04/gate.default.json}" "$STATE/gate.rules.json"
      eval "sandboxed gate query $PA $GR --allow $(q "$STATE") --exec -- $R04 phase gate --state $(q "$STATE") $PA --gate $(q "$STATE/gate.rules.json") $(q "$REPO")" && rc=0 || rc=$?
      if [ $rc -eq 3 ]; then rec_skip build gate-blocked
      elif [ $rc -ne 0 ]; then rec_skip build gate-failed
      else
        # The build sandbox runs third-party code. It gets copies of the phase inputs in its own
        # state dir and never sees the main state; only its outputs are copied back.
        for f in detect.json fetch.json gate.json; do cp "$STATE/$f" "$SBUILD/$f"; done
        PERM=""; [ $PERMISSIVE -eq 0 ] || PERM=--permissive
        NB=""; [ $NO_BUILD -eq 0 ] || NB=--no-build
        eval "sandboxed build build $PA $PERM $GR --allow $(q "$SBUILD") --exec -- $R04 phase build --state $(q "$SBUILD") $PA --build $(q "$BUILD_SEL") $NB $(q "$REPO")" && rc=0 || rc=$?
        for f in build.json build.stdout.json build.stderr.log; do [ ! -f "$SBUILD/$f" ] || cp "$SBUILD/$f" "$STATE/$f"; done
      fi
    fi
  else
    # --native: 07's npm-fetch (install --ignore-scripts) then native-build (rebuild); no vlt gate
    case $(jq -r '.detected // ""' "$STATE/detect.json") in pnpm) TOOL=pnpm ;; bun) TOOL=bun ;; *) TOOL=npm ;; esac
    XA=""; [ "$TOOL" != pnpm ] || XA="-- --ignore-pnpmfile"
    eval "sandboxed fetch npm-fetch $PA --tool $TOOL $XA" && rc=0 || rc=$?
    rec_skip gate native-mode
    if [ $rc -ne 0 ]; then rec_skip build fetch-failed
    elif [ $NO_BUILD -eq 1 ]; then rec_skip build no-build
    else eval "sandboxed build native-build $PA --tool $TOOL" || true; fi
  fi
  # 04's report phase reads the state files and lockfile checksums; it runs under the read-only
  # query sandbox because the project may now contain anything a build script wrote
  eval "sandboxed report query $PA $GR --allow $(q "$STATE") --exec -- $R04 phase report --state $(q "$STATE") $PA $(q "$REPO")" || true
fi

# ---------------------------------------------------------------- merge
mkdir -p "$OUT"
OUT=$(CDPATH= cd -- "$OUT" && pwd -P)
REPORT=$OUT/$SLUG-$(date -u +%Y%m%dT%H%M%SZ).json
INSTALL=null; [ ! -f "$STATE/report.json" ] || INSTALL=$(cat "$STATE/report.json")
jq -n --arg impl "$IMPL" --arg now "$(date -u +%Y-%m-%dT%H:%M:%SZ)" --arg src "$SOURCE" --arg kind "$KIND" \
  --arg ref "$REF" --arg commit "$COMMIT" --arg slug "$SLUG" --arg mode "$( [ $NATIVE -eq 1 ] && echo native || echo vlt)" \
  --arg prof "$PROFILE_NAME" --arg gate "$GATE" --arg build "$BUILD_SEL" --argjson nb $NO_BUILD --argjson perm $PERMISSIVE \
  --arg scr "$SCR" --argjson keep $KEEP --slurpfile aq "$SCR/acquire.json" --argjson install "$INSTALL" \
  --slurpfile pa "$PH/acquire.json" --slurpfile pd "$PH/detect.json" --slurpfile pf "$PH/fetch.json" \
  --slurpfile pg "$PH/gate.json" --slurpfile pb "$PH/build.json" --slurpfile pr "$PH/report.json" '
  def nz: if . == "" then null else . end;
  {acquire: $pa[0], detect: $pd[0], fetch: $pf[0], gate: $pg[0], build: $pb[0], report: $pr[0]} as $ph
  | {
      schemaVersion: 1, tool: "fork-install", implementation: $impl, generatedAt: $now,
      input: {source: $src, kind: $kind, ref: ($ref | nz), commit: ($commit | nz), slug: $slug},
      mode: $mode,
      options: {profile: $prof, gate: ($gate | nz), build: $build, noBuild: ($nb == 1), permissive: ($perm == 1)},
      scratch: {dir: $scr, kept: ($keep == 1)},
      acquire: $aq[0],
      phases: $ph,
      install: $install,
      exit: ([$ph.acquire, $ph.detect, $ph.fetch, $ph.gate, $ph.build] | map(select(.ran) | .exit) | map(select(. != 0)) | .[0]
             // (if $ph.report.ran and $ph.report.exit != 0 then 1 else 0 end))
    }' >"$REPORT"

# ---------------------------------------------------------------- summary
{
  jq -r '"fork-install \(.implementation): \(.input.source)\(if .input.commit then " @ " + .input.commit[0:12] else "" end) (mode \(.mode), profile \(.options.profile))"' "$REPORT"
  printf '%-8s %-5s %-8s %-28s %s\n' phase exit ms sandbox network
  jq -r '.phases | to_entries[] | [.key, (if .value.ran then (.value.exit | tostring) else "-" end),
      (if .value.ran then (.value.durationMs | tostring) else (.value.skipReason // "-") end),
      (.value.sandbox.profile // "-" | split("/") | last),
      (if .value.sandbox == null then "-" elif .value.sandbox.network == "block" then "blocked"
       else "allowed \(.value.sandbox.networkAllowed // "?"), denied \(.value.sandbox.networkDenied // [] | map(.count) | add // 0)" end)] | @tsv' "$REPORT" \
    | while IFS="$(printf '\t')" read -r a b c d e; do printf '%-8s %-5s %-8s %-28s %s\n' "$a" "$b" "$c" "$d" "$e"; done
  jq -r '"exit \(.exit); built: \(if .mode == "native" then "n/a (native rebuild, see logs)" else (.install.build.built // [] | map("\(.name)@\(.version)") | join(", ") | if . == "" then "none" else . end) end)"' "$REPORT"
  printf 'report: %s\n' "$REPORT"
} >&2
[ $KEEP -eq 0 ] || vl_log "kept scratch dir $SCR"
printf '%s\n' "$REPORT"
exit "$(jq -r .exit "$REPORT")"
