# registry-profile.nu: Nushell port of packages/registry-profile (TypeScript reference).
# Output must stay byte-identical to the reference; `just conformance` checks it.
#
#   use lib/nu/registry-profile.nu
#   registry-profile render npmrc vlt-hosted
#   registry-profile list

const BUILD_TARGET = ":scripts:not(:built):not(:malware)"
const TARGETS = [npmrc bunfig yarnrc vlt-json env-sh env-nu hosts]
const LIB_DIR = path self .

def default-file []: nothing -> path {
  $env.VLT_LAB_PROFILES? | default ($LIB_DIR | path join .. .. config registry.profiles.json | path expand)
}

def substitute [name: string]: string -> string {
  let s = $in
  let keys = $s | parse --regex '\{env:(?<k>[A-Za-z_][A-Za-z0-9_]*)\}' | get k | uniq
  $keys | reduce --fold $s {|k, acc|
    let v = $env | get --optional $k | default ""
    if ($v | is-empty) { error make --unspanned { msg: $"profile ($name): environment variable ($k) is not set" } }
    $acc | str replace --all $"{env:($k)}" $v
  }
}

def host-of []: string -> string { $in | parse --regex '^https?://(?<h>[^/]+)/' | get 0.h }

# Load and validate the profiles document.
export def load [file?: path]: nothing -> record {
  let doc = open --raw ($file | default (default-file)) | from json
  if ($doc.default not-in ($doc.profiles | columns)) { error make --unspanned { msg: "default must name a profile" } }
  $doc
}

# Resolve a profile: substitute placeholders and derive the sandbox host list.
export def resolve [name?: string, --file: path]: nothing -> record {
  let doc = load $file
  let chosen = $name | default ($env.VLT_LAB_PROFILE? | default $doc.default)
  if ($chosen not-in ($doc.profiles | columns)) {
    error make --unspanned { msg: $"unknown profile ($chosen); available: ($doc.profiles | columns | str join ', ')" }
  }
  let p = $doc.profiles | get $chosen
  let npm = $p.npm | substitute $chosen
  let main = if ($p.main? | is-empty) { null } else { $p.main | substitute $chosen }
  let scope = if ($p.scope? | is-empty) { null } else { $p.scope | substitute $chosen }
  let extra = $p.hosts? | default [] | each { substitute $chosen }
  let hosts = [($npm | host-of)] | append (if $main == null { [] } else { [($main | host-of)] }) | append $extra | uniq
  {
    name: $chosen, npm: $npm, main: $main, scope: $scope,
    tokenEnv: ($p.tokenEnv? | default null), hosts: $hosts,
    scripts: ($p.scripts? | default deny)
  }
}

def lines [xs: list]: nothing -> string { ($xs | where {|x| $x != null } | str join "\n") + "\n" }
def header [r: record]: nothing -> string { $"# generated by vlt-lab from profile ($r.name); do not edit" }
def routed [r: record]: nothing -> bool { $r.main != null and $r.scope != null }
def auth-key [url: string]: nothing -> string { $url | str replace --regex '^https?:' '' }
def opt [cond: bool, value: any]: nothing -> any { if $cond { $value } else { null } }

def npmrc [r: record]: nothing -> string {
  let tok = $r.tokenEnv
  lines [
    (header $r)
    $"registry=($r.npm)"
    (opt (routed $r) $"($r.scope):registry=($r.main)")
    (opt ($tok != null) $"(auth-key $r.npm):_authToken=${($tok)}")
    (opt ($tok != null and $r.main != null) $"(auth-key ($r.main | default '')):_authToken=${($tok)}")
    (opt ($r.scripts == deny) "ignore-scripts=true")
  ]
}

def toml-registry [url: string, tok: any]: nothing -> string {
  if $tok == null { $"\"($url)\"" } else { $"{ url = \"($url)\", token = \"$($tok)\" }" }
}

def bunfig [r: record]: nothing -> string {
  let scoped = routed $r
  lines [
    (header $r)
    "[install]"
    $"registry = (toml-registry $r.npm $r.tokenEnv)"
    (opt $scoped "")
    (opt $scoped "[install.scopes]")
    (opt $scoped $"\"($r.scope | default '@' | str substring 1..)\" = (toml-registry ($r.main | default '') $r.tokenEnv)")
  ]
}

def yarn-auth [indent: string, tok: any]: nothing -> list {
  if $tok == null { [] } else { [$"($indent)npmAlwaysAuth: true" $"($indent)npmAuthToken: \"${($tok):-}\""] }
}

def yarnrc [r: record]: nothing -> string {
  let http = [$r.npm $r.main] | where {|u| $u != null and ($u | str starts-with "http:") }
    | each { host-of | str replace --regex ':\d+$' '' } | uniq
  let scopes = if (routed $r) {
    [
      "npmScopes:"
      $"  ($r.scope | str substring 1..):"
      $"    npmRegistryServer: \"($r.main)\""
      $"    npmPublishRegistry: \"($r.main)\""
    ] | append (yarn-auth "    " $r.tokenEnv)
  } else { [] }
  let unsafe = if ($http | is-empty) { [] } else { ["unsafeHttpWhitelist:"] | append ($http | each {|h| $"  - \"($h)\"" }) }
  lines ([(header $r) $"npmRegistryServer: \"($r.npm)\""]
    | append (yarn-auth "" $r.tokenEnv)
    | append $scopes
    | append (opt ($r.scripts == deny) "enableScripts: false")
    | append $unsafe)
}

def vlt-json [r: record]: nothing -> string {
  let registries = if $r.main == null { {npm: $r.npm} } else { {npm: $r.npm, main: $r.main} }
  let base = {registries: $registries}
  let scoped = if (routed $r) { $base | insert scoped-registries { {($r.scope): $r.main} } } else { $base }
  let config = $scoped | insert command {build: {target: $BUILD_TARGET}}
  ({config: $config} | to json --indent 2) + "\n"
}

# Environment pairs in the reference order.
export def env-pairs [r: record]: nothing -> list {
  let registries = if $r.main == null { $"npm=($r.npm)" } else { $"npm=($r.npm)\nmain=($r.main)" }
  [
    [npm_config_registry $r.npm]
    [NPM_CONFIG_REGISTRY $r.npm]
    [YARN_REGISTRY $r.npm]
    [YARN_NPM_REGISTRY_SERVER $r.npm]
    [VLT_REGISTRY $r.npm]
    [VLT_REGISTRIES $registries]
  ]
  | append (if (routed $r) { [[VLT_SCOPED_REGISTRIES $"($r.scope)=($r.main)"]] } else { [] })
  | append (if $r.scripts == deny { [[npm_config_ignore_scripts "true"] [YARN_ENABLE_SCRIPTS "false"] [YARN_IGNORE_SCRIPTS "true"]] } else { [] })
}

def env-sh [r: record]: nothing -> string {
  lines ([(header $r)] | append (env-pairs $r | each {|kv| $"export ($kv.0)='($kv.1)'" }))
}

def env-nu [r: record]: nothing -> string {
  lines ([(header $r)] | append (env-pairs $r | each {|kv| $"$env.($kv.0) = \"($kv.1 | str replace --all "\n" '\n')\"" }))
}

# Render one target for a profile (defaults: $VLT_LAB_PROFILE, then the document default).
export def render [target: string, name?: string, --file: path]: nothing -> string {
  if ($target not-in $TARGETS) {
    error make --unspanned { msg: $"unknown target ($target); expected one of: ($TARGETS | str join ', ')" }
  }
  let r = resolve $name --file $file
  match $target {
    npmrc => (npmrc $r)
    bunfig => (bunfig $r)
    yarnrc => (yarnrc $r)
    vlt-json => (vlt-json $r)
    env-sh => (env-sh $r)
    env-nu => (env-nu $r)
    hosts => (lines $r.hosts)
  }
}

# Profile names and descriptions.
export def list [--file: path]: nothing -> table {
  load $file | get profiles | transpose name p | each {|row| {name: $row.name, description: ($row.p.description? | default "")} }
}

# Load a profile's environment into the caller: `registry-profile env vlt-hosted | load-env`.
export def env [name?: string, --file: path]: nothing -> record {
  env-pairs (resolve $name --file $file) | reduce --fold {} {|kv, acc| $acc | insert $kv.0 $kv.1 }
}
